/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.IU;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class AgregarProductoGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarProductoGUI.class.getName());
    private String nombreUsuario;
    private String rolUsuario;
    private javax.swing.JButton btnActivo = null;
    private java.util.ArrayList<pizzeria.model.Producto> productosMostrados = new java.util.ArrayList<>();

    /**
     * Creates new form MenuGerente
     */
        public AgregarProductoGUI() {
            initComponents();

            this.rolUsuario = "Cajero";
            this.nombreUsuario = "";

            inicializarVentanaAgregarProducto();
        }

        public AgregarProductoGUI(String rol, String nombre) {
            initComponents();

            this.rolUsuario = rol;
            this.nombreUsuario = nombre;

            inicializarVentanaAgregarProducto();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rol = new javax.swing.JLabel();
        BarraNav = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        PiePag = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Interfaz = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        Encabezado.setBackground(new java.awt.Color(168, 27, 29));
        Encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LA CASA DEL SABOR");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("LOGO");
        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIZZERIA");

        Rol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rol.setForeground(new java.awt.Color(255, 255, 255));
        Rol.setText("Cajero");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BarraNav.setBackground(new java.awt.Color(28, 28, 28));
        BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnInicio.setBackground(new java.awt.Color(168, 27, 29));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ventas");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnUsuarios.setBackground(new java.awt.Color(28, 28, 28));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Reservas");
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnReportes.setBackground(new java.awt.Color(28, 28, 28));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Ver Menu");
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(28, 28, 28));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout BarraNavLayout = new javax.swing.GroupLayout(BarraNav);
        BarraNav.setLayout(BarraNavLayout);
        BarraNavLayout.setHorizontalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BarraNavLayout.setVerticalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PiePag.setBackground(new java.awt.Color(28, 28, 28));
        PiePag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Powered by StarTech");

        jLabel5.setText("Logo");

        javax.swing.GroupLayout PiePagLayout = new javax.swing.GroupLayout(PiePag);
        PiePag.setLayout(PiePagLayout);
        PiePagLayout.setHorizontalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PiePagLayout.setVerticalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGroup(PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        Interfaz.setBackground(new java.awt.Color(255, 255, 255));
        Interfaz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jButton1.setBackground(new java.awt.Color(168, 27, 29));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AGREGAR AL PEDIDO");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton2.setText("VOLVER AL PEDIDO");
        jButton2.setToolTipText("");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel7.setText("Busca por nombre o filtra por categoría.");

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(168, 27, 29));
        jLabel19.setText("AGREGAR PRODUCTO");

        jLabel3.setText("Categoria");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Pizzas", "Bebidas" }));

        jLabel6.setText("Buscar producto:");

        jLabel8.setText("Cantidad");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel9.setText("LISTA DE PRODUCTOS");

        jTable1.setFont(new java.awt.Font("Liberation Sans", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pizza Hawaiana", "Pizza", "Bs. 35"},
                {"Pizza Pepperoni", "Pizza", "Bs. 38"},
                {"Gaseosa 1.5 L", "Bebida", "Bs. 10"},
                {"Jugo Natural", "Bebida", "Bs. 8"}
            },
            new String [] {
                "Producto", "Categoria", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InterfazLayout = new javax.swing.GroupLayout(Interfaz);
        Interfaz.setLayout(InterfazLayout);
        InterfazLayout.setHorizontalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InterfazLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(217, 217, 217)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(InterfazLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InterfazLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(188, 188, 188)))
                        .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        InterfazLayout.setVerticalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(47, 47, 47)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(BarraNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarraNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PiePag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        new VentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new ConsultarReservasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FrameVerMenu ventana = new FrameVerMenu(rolUsuario, nombreUsuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this, "¿Desea cerrar sesión?", "Cerrar Sesión",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        new LoginGUI().setVisible(true);
    }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un producto de la tabla.",
                    "Producto no seleccionado",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int filaModelo = jTable1.convertRowIndexToModel(fila);

        if (filaModelo < 0 || filaModelo >= productosMostrados.size()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se pudo identificar el producto seleccionado.",
                    "Error de selección",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int cantidad = (int) jSpinner1.getValue();

        pizzeria.model.Producto productoSeleccionado = productosMostrados.get(filaModelo);

        String error = ContextoVentasGUI.getInstancia()
                .getGestorVenta()
                .agregarItemGUI(productoSeleccionado, cantidad);

        if (error != null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    error,
                    "No se pudo agregar producto",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

                javax.swing.JOptionPane.showMessageDialog(
                this,
                "Producto agregado al pedido correctamente.",
                "Producto agregado",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        new NuevoPedidoGUI(rolUsuario, nombreUsuario).setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new NuevoPedidoGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void inicializarVentanaAgregarProducto() {
    aplicarEstructuraVisualCajero();
    reconstruirInterfazAgregarProducto();

    mostrarUsuario();
    configurarHover();
    activarBoton(btnInicio);

    configurarTablaProductos();
    cargarProductos();
    configurarFiltrosProductos();

    cargarImagen(lblLogo, "resources/imagenes/logoCasaDelSabor.jpeg");
}
    
    
    private void aplicarEstructuraVisualCajero() {
    setSize(1280, 720);
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setMaximumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setResizable(false);
    setLocationRelativeTo(null);

    if (lblLogo != null) {
        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));
        lblLogo.setMinimumSize(new java.awt.Dimension(75, 75));
        lblLogo.setMaximumSize(new java.awt.Dimension(75, 75));
    }

    Encabezado.setPreferredSize(new java.awt.Dimension(1280, 100));
    Encabezado.setMinimumSize(new java.awt.Dimension(1280, 100));

    PiePag.setPreferredSize(new java.awt.Dimension(1280, 47));
    PiePag.setMinimumSize(new java.awt.Dimension(1280, 47));

    BarraNav.setPreferredSize(new java.awt.Dimension(280, 573));
    BarraNav.setMinimumSize(new java.awt.Dimension(280, 573));
    BarraNav.setMaximumSize(new java.awt.Dimension(280, 573));

    Interfaz.setPreferredSize(new java.awt.Dimension(1000, 573));
    Interfaz.setMinimumSize(new java.awt.Dimension(1000, 573));
    Interfaz.setBackground(java.awt.Color.WHITE);

    reconstruirEstructuraBaseCajero();

    revalidate();
    repaint();
}
    
    
    
    private void reconstruirEstructuraBaseCajero() {
    getContentPane().removeAll();

    Fondo.removeAll();
    Fondo.setLayout(new java.awt.BorderLayout(0, 0));
    Fondo.setBackground(java.awt.Color.WHITE);

    configurarBarraLateral();

    javax.swing.JPanel cuerpo = new javax.swing.JPanel(new java.awt.BorderLayout(0, 0));
    cuerpo.setBackground(java.awt.Color.WHITE);
    cuerpo.setPreferredSize(new java.awt.Dimension(1280, 573));
    cuerpo.add(BarraNav, java.awt.BorderLayout.WEST);
    cuerpo.add(Interfaz, java.awt.BorderLayout.CENTER);

    Fondo.add(Encabezado, java.awt.BorderLayout.NORTH);
    Fondo.add(cuerpo, java.awt.BorderLayout.CENTER);
    Fondo.add(PiePag, java.awt.BorderLayout.SOUTH);

    setContentPane(Fondo);
}
    
    
    private void configurarBarraLateral() {
    BarraNav.removeAll();
    BarraNav.setLayout(new javax.swing.BoxLayout(BarraNav, javax.swing.BoxLayout.Y_AXIS));
    BarraNav.setBackground(new java.awt.Color(28, 28, 28));
    BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

    java.awt.Dimension tamBoton = new java.awt.Dimension(250, 60);

    configurarBotonLateral(btnInicio, tamBoton);
    configurarBotonLateral(btnUsuarios, tamBoton);
    configurarBotonLateral(btnReportes, tamBoton);
    configurarBotonLateral(btnCerrar, tamBoton);

    BarraNav.add(javax.swing.Box.createVerticalStrut(58));
    BarraNav.add(btnInicio);
    BarraNav.add(javax.swing.Box.createVerticalStrut(60));
    BarraNav.add(btnUsuarios);
    BarraNav.add(javax.swing.Box.createVerticalStrut(49));
    BarraNav.add(btnReportes);
    BarraNav.add(javax.swing.Box.createVerticalStrut(55));
    BarraNav.add(btnCerrar);
    BarraNav.add(javax.swing.Box.createVerticalGlue());
}
    private void configurarBotonLateral(javax.swing.JButton boton, java.awt.Dimension tamano) {
    boton.setPreferredSize(tamano);
    boton.setMinimumSize(tamano);
    boton.setMaximumSize(tamano);

    boton.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    boton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

    boton.setFocusPainted(false);
    boton.setContentAreaFilled(true);
    boton.setOpaque(true);
    boton.setBorderPainted(false);
}
    
    
    private void reconstruirInterfazAgregarProducto() {
    Interfaz.removeAll();
    Interfaz.setLayout(new java.awt.BorderLayout());
    Interfaz.setBackground(java.awt.Color.WHITE);
    Interfaz.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 45, 25, 45));

    javax.swing.JPanel panelContenido = new javax.swing.JPanel();
    panelContenido.setOpaque(false);
    panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));

    javax.swing.JPanel panelBotones = new javax.swing.JPanel(new java.awt.BorderLayout());
    panelBotones.setOpaque(false);
    panelBotones.setMaximumSize(new java.awt.Dimension(820, 42));
    panelBotones.setPreferredSize(new java.awt.Dimension(820, 42));
    panelBotones.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jButton2.setPreferredSize(new java.awt.Dimension(180, 40));
    jButton1.setPreferredSize(new java.awt.Dimension(220, 40));

    panelBotones.add(jButton2, java.awt.BorderLayout.WEST);
    panelBotones.add(jButton1, java.awt.BorderLayout.EAST);

    jLabel19.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    jLabel7.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    javax.swing.JPanel panelFiltros = new javax.swing.JPanel(new java.awt.GridLayout(1, 3, 40, 0));
    panelFiltros.setOpaque(false);
    panelFiltros.setMaximumSize(new java.awt.Dimension(820, 65));
    panelFiltros.setPreferredSize(new java.awt.Dimension(820, 65));
    panelFiltros.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    javax.swing.JPanel panelCategoria = crearBloqueFiltro(jLabel3, jComboBox1);
    javax.swing.JPanel panelBuscar = crearBloqueFiltro(jLabel6, jTextField1);
    javax.swing.JPanel panelCantidad = crearBloqueFiltro(jLabel8, jSpinner1);

    jComboBox1.setPreferredSize(new java.awt.Dimension(170, 32));
    jTextField1.setPreferredSize(new java.awt.Dimension(300, 32));
    jSpinner1.setPreferredSize(new java.awt.Dimension(80, 32));

    panelFiltros.add(panelCategoria);
    panelFiltros.add(panelBuscar);
    panelFiltros.add(panelCantidad);

    reconstruirPanelListaProductos();

    panelContenido.add(panelBotones);
    panelContenido.add(javax.swing.Box.createVerticalStrut(16));
    panelContenido.add(jLabel19);
    panelContenido.add(javax.swing.Box.createVerticalStrut(6));
    panelContenido.add(jLabel7);
    panelContenido.add(javax.swing.Box.createVerticalStrut(26));
    panelContenido.add(panelFiltros);
    panelContenido.add(javax.swing.Box.createVerticalStrut(16));
    panelContenido.add(jPanel2);

    Interfaz.add(panelContenido, java.awt.BorderLayout.CENTER);

    Interfaz.revalidate();
    Interfaz.repaint();
}
    
    
    
    private javax.swing.JPanel crearBloqueFiltro(javax.swing.JLabel etiqueta, java.awt.Component campo) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setOpaque(false);
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));

        etiqueta.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        campo.setMaximumSize(new java.awt.Dimension(320, 32));
        campo.setPreferredSize(new java.awt.Dimension(320, 32));

        panel.add(etiqueta);
        panel.add(javax.swing.Box.createVerticalStrut(6));
        panel.add(campo);

        return panel;
    }
    
    private void reconstruirPanelListaProductos() {
    jPanel2.removeAll();
    jPanel2.setBackground(java.awt.Color.WHITE);
    jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)),
            javax.swing.BorderFactory.createEmptyBorder(18, 22, 18, 22)
    ));
    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
    jPanel2.setMaximumSize(new java.awt.Dimension(820, 245));
    jPanel2.setPreferredSize(new java.awt.Dimension(820, 245));
    jPanel2.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jLabel9.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jScrollPane1.setPreferredSize(new java.awt.Dimension(770, 175));
    jScrollPane1.setMaximumSize(new java.awt.Dimension(770, 175));
    jScrollPane1.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jPanel2.add(jLabel9);
    jPanel2.add(javax.swing.Box.createVerticalStrut(10));
    jPanel2.add(jScrollPane1);

    jPanel2.revalidate();
    jPanel2.repaint();
}
    
    
   private void configurarTablaProductos() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{
                "Producto", "Categoría", "Precio"
            }
    ) {
        boolean[] canEdit = new boolean[]{
            false, false, false
        };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    jTable1.setModel(modelo);
    jTable1.setRowHeight(25);
    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    if (jTable1.getColumnModel().getColumnCount() >= 3) {
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(360);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
    }
} 
    
    
    
    
    private void mostrarUsuario() {
    
            if (rolUsuario == null || rolUsuario.trim().isEmpty()) {
           rolUsuario = "Cajero";
       }

       if (nombreUsuario == null) {
           nombreUsuario = "";
       }

       if (nombreUsuario.trim().isEmpty()) {
           Rol.setText(rolUsuario);
       } else {
           Rol.setText(rolUsuario + ": " + nombreUsuario);
       }
    }
    
    private void cargarPanel(javax.swing.JPanel panel) {
        Interfaz.removeAll();                    // limpia el contenido anterior
        Interfaz.setLayout(new java.awt.BorderLayout());
        Interfaz.add(panel, java.awt.BorderLayout.CENTER);
        Interfaz.revalidate();                   // refresca el layout
        Interfaz.repaint();                      // redibuja
    }
    private void configurarHover() {
        javax.swing.JButton[] botones = {
            btnInicio,
            btnUsuarios,
            btnReportes,
            btnCerrar
        };
    
        for (javax.swing.JButton b : botones) {
            b.setContentAreaFilled(true);
            b.setOpaque(true);
            b.setBorderPainted(false);
            b.setBackground(java.awt.Color.WHITE);
            b.setForeground(new java.awt.Color(60, 60, 60));
        
            b.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(230, 230, 230));
            b.setForeground(new java.awt.Color(168, 27, 29)); // #A81B1D
        }
    }
    @Override
    public void mouseExited(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            b.setForeground(new java.awt.Color(60, 60, 60));
        }
    }
});
        }
    }
    
    private void activarBoton(javax.swing.JButton boton) {
    // Resetea el anterior
        if (btnActivo != null) {
            btnActivo.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            btnActivo.setForeground(new java.awt.Color(60, 60, 60));
        }
        boton.setBackground(new java.awt.Color(168, 27, 29)); // #A81B1D
        boton.setForeground(new java.awt.Color(255, 255, 255)); // #FFFFFF
        btnActivo = boton;
    }
    
    
   private void cargarProductos() {
        cargarProductos("", "Todas");
    }

    private void cargarProductos(String filtroTexto, String categoriaSeleccionada) {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);
        productosMostrados.clear();

        java.util.ArrayList<pizzeria.model.Producto> productos =
                ContextoVentasGUI.getInstancia().getMenu().getProductos();

        String filtro = filtroTexto == null ? "" : filtroTexto.trim().toLowerCase();
        String categoria = categoriaSeleccionada == null ? "Todas" : categoriaSeleccionada.trim();

        for (pizzeria.model.Producto producto : productos) {
            String nombre = producto.getNombre();
            String categoriaReal = producto.getTipo().getNombre();
            String categoriaVisual = obtenerCategoriaVisual(producto);

            boolean coincideTexto = filtro.isEmpty()
                    || nombre.toLowerCase().contains(filtro)
                    || categoriaReal.toLowerCase().contains(filtro)
                    || categoriaVisual.toLowerCase().contains(filtro);

            boolean coincideCategoria = categoria.equalsIgnoreCase("Todas")
                    || categoria.isBlank()
                    || categoriaVisual.equalsIgnoreCase(categoria);

            if (!coincideTexto || !coincideCategoria) {
                continue;
            }

            productosMostrados.add(producto);

            modelo.addRow(new Object[]{
                producto.getNombre(),
                categoriaVisual,
                "Bs. " + String.format("%.2f", producto.getPrecio())
            });
        }
    }
    
    private String obtenerCategoriaVisual(pizzeria.model.Producto producto) {
        String tipo = producto.getTipo().getNombre();

        if (tipo == null) {
            return "Producto";
        }

        String tipoLower = tipo.toLowerCase();
        String nombreLower = producto.getNombre().toLowerCase();

        if (tipoLower.contains("bebida")
                || tipoLower.contains("refresco")
                || nombreLower.contains("gaseosa")
                || nombreLower.contains("coca")
                || nombreLower.contains("jugo")
                || nombreLower.contains("agua")
                || nombreLower.contains("refresco")) {
            return "Bebidas";
        }

        return "Pizzas";
    }

    private void configurarFiltrosProductos() {
        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                aplicarFiltrosProductos();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                aplicarFiltrosProductos();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                aplicarFiltrosProductos();
            }
        });

        jComboBox1.addActionListener(e -> aplicarFiltrosProductos());
    }
    
    
    private void aplicarFiltrosProductos() {
        String texto = jTextField1.getText().trim();
        String categoria = jComboBox1.getSelectedItem() == null
                ? "Todas"
                : jComboBox1.getSelectedItem().toString();

        cargarProductos(texto, categoria);
    }
    
    private void cargarImagen(JLabel label, String ruta){
     label.setText("");
    try {
        java.io.File archivo = new java.io.File(ruta);
        if (!archivo.exists()) {
            System.err.println("Imagen no encontrada: " + ruta);
            return;
        }
        ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());
        Image imgEscalada = icono.getImage().getScaledInstance(
            label.getPreferredSize().width,
            label.getPreferredSize().height,
            Image.SCALE_SMOOTH
        );
        label.setIcon(new ImageIcon(imgEscalada));
    } catch (Exception e) {
        System.err.println("Error cargando imagen: " + e.getMessage());
    }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarProductoGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNav;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Interfaz;
    private javax.swing.JPanel PiePag;
    private javax.swing.JLabel Rol;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
