/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.IU;

import pizzeria.model.Insumo;
import pizzeria.model.Inventario;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author BENJAMIN
 */
public class BuscarInsumos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscarInsumos.class.getName());
    private final Inventario inventario = new Inventario();
    private Image logoImagen;
    private String rolUsuario;
    private String nombreUsuario;
    /**
     * Creates new form BuscarInsumos
     */
    public Inventario getInventario() {
        return inventario;
    }
    public BuscarInsumos() {
        initComponents();
        inventario.cargarArchivo();
        cargarLogo();
        configurarLogo();
        configurarBotones();
        configurarEncabezado();
        configurarTabla();
        configurarEstiloTabla();
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 90));
        cargarImagen(jLabel8, "resources/imagenes/logoCasaDelSabor.jpeg");
    }
    
    public BuscarInsumos(String rol, String nombre) {
        initComponents();
        this.rolUsuario = rol;
        this.nombreUsuario = nombre;
        Rol1.setText(rol + ": " + nombre);
        inventario.cargarArchivo();
        cargarLogo();
        configurarLogo();
        configurarBotones();
        configurarEncabezado();
        configurarTabla();
        configurarEstiloTabla();
        mostrarUsuario();
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 90));
        cargarImagen(jLabel8, "resources/imagenes/logoCasaDelSabor.jpeg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraNav = new javax.swing.JPanel();
        btnFinanzas = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnInvetario = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        PiePag = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Encabezado1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Rol1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraNav.setBackground(new java.awt.Color(0, 0, 0));
        BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnFinanzas.setBackground(new java.awt.Color(0, 0, 0));
        btnFinanzas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFinanzas.setForeground(new java.awt.Color(255, 255, 255));
        btnFinanzas.setText("Modificar Insumo");
        btnFinanzas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanzas.addActionListener(this::btnModificarInsumoActionPerformed);

        btnMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Actualizar Stock");
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu.addActionListener(this::btnActualizarStockActionPerformed);

        btnInvetario.setBackground(new java.awt.Color(0, 0, 0));
        btnInvetario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInvetario.setForeground(new java.awt.Color(255, 255, 255));
        btnInvetario.setText("Eliminar Insumo");
        btnInvetario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInvetario.addActionListener(this::btnEliminarInsumoActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Volver");
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.addActionListener(this::btnVolverActionPerformed);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        javax.swing.GroupLayout BarraNavLayout = new javax.swing.GroupLayout(BarraNav);
        BarraNav.setLayout(BarraNavLayout);
        BarraNavLayout.setHorizontalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinanzas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvetario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BarraNavLayout.setVerticalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvetario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        PiePag.setBackground(new java.awt.Color(0, 0, 0));
        PiePag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        PiePag.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Powered by StarTech");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Logo");

        javax.swing.GroupLayout PiePagLayout = new javax.swing.GroupLayout(PiePag);
        PiePag.setLayout(PiePagLayout);
        PiePagLayout.setHorizontalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PiePagLayout.setVerticalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGroup(PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Encabezado1.setBackground(new java.awt.Color(168, 27, 29));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LA CASA DEL SABOR");

        jLabel8.setText("LOGO");
        jLabel8.setPreferredSize(new java.awt.Dimension(86, 74));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("PIZZERIA");

        Rol1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Rol1.setText("Rol: Usuario");

        javax.swing.GroupLayout Encabezado1Layout = new javax.swing.GroupLayout(Encabezado1);
        Encabezado1.setLayout(Encabezado1Layout);
        Encabezado1Layout.setHorizontalGroup(
            Encabezado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Encabezado1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Encabezado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Encabezado1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 632, Short.MAX_VALUE)
                        .addComponent(Rol1))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        Encabezado1Layout.setVerticalGroup(
            Encabezado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Encabezado1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(Encabezado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado1Layout.createSequentialGroup()
                        .addGroup(Encabezado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rol1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Encabezado1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addComponent(PiePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Encabezado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Encabezado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PiePag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla(){
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
    new String[]{"ID", "Nombre", "Unidad", "Stock", "Stock Minimo", "Precio de Compra", "Cantidad por Pizza"}, 0
    ){
        @Override
        public boolean isCellEditable(int row, int column){
            return column !=0;
        }
    };
    for(Insumo ins : inventario.getInsumos()){
        modelo.addRow(new Object[]{
            ins.getId(),
            ins.getNombre(),
            ins.getUnidad(),
            String.format("%.2f", ins.getStockActual()),
            String.format("%.2f", ins.getStockMinimo()),
            String.format("%.2f", ins.getPrecioCompra()),
            String.format("%.2f", ins.getCantidadPorPizza())
        });
    }
    jTable1.setModel(modelo);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
    jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
    jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
    jTable1.getColumnModel().getColumn(5).setPreferredWidth(120);
    jTable1.getColumnModel().getColumn(6).setPreferredWidth(120);
}
    
    private void cargarLogo() {
    try {
        String rutaLogoPng = "resources/imagenes/LogoPizzeria.png";
        String rutaLogoJpg = "resources/imagenes/LogoPizzeria.jpg";
        File archivoLogoPng = new File(rutaLogoPng);
        File archivoLogoJpg = new File(rutaLogoJpg);

        if (archivoLogoPng.exists()) {
            logoImagen = new ImageIcon(archivoLogoPng.getAbsolutePath()).getImage();
        } else if (archivoLogoJpg.exists()) {
            logoImagen = new ImageIcon(archivoLogoJpg.getAbsolutePath()).getImage();
        }
        } catch (Exception e) {
            logoImagen = null;
        }
    }
    
    private void configurarLogo() {
        if (logoImagen != null) {
            Image logoEscalado = logoImagen.getScaledInstance(70, 70, Image.SCALE_SMOOTH);
            jLabel8.setIcon(new ImageIcon(logoEscalado));
            jLabel8.setText("");
        }
    }
    
    private void configurarBotones() {
        javax.swing.JButton[] botones = {btnFinanzas, btnMenu, btnInvetario, btnCerrar};
    
        for (javax.swing.JButton b : botones) {
            b.setBackground(new Color(0, 0, 0));
            b.setForeground(Color.WHITE);
            b.setFont(new Font("Segoe UI", Font.PLAIN, 15));
            b.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 10));
            b.setFocusPainted(false);
            b.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
            b.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    b.setBackground(new Color(168, 27, 29));
                    b.setForeground(Color.WHITE);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    b.setBackground(new Color(0, 0, 0));
                    b.setForeground(Color.WHITE);
                }
            });
        }
    }
    
    private void mostrarUsuario() {
    
        Rol1.setText(rolUsuario + ": " + nombreUsuario);
    }
    
    private void configurarEstiloTabla() {
    jTable1.getTableHeader().setBackground(new Color(0, 0, 0));
    jTable1.getTableHeader().setForeground(Color.BLACK);
    jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
    jTable1.getTableHeader().setPreferredSize(new Dimension(0, 35));

    jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (isSelected) {
                    setBackground(new Color(168, 27, 29));
                    setForeground(Color.WHITE);
                } else if (row % 2 == 0) {
                    setBackground(new Color(245, 245, 245));
                    setForeground(Color.BLACK);
                } else {
                    setBackground(Color.WHITE);
                    setForeground(Color.BLACK);
                }
                setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 5));
                return this;
            }
        });

        jTable1.setRowHeight(30);
        jTable1.setShowGrid(false);
        jTable1.setIntercellSpacing(new Dimension(0, 0));
    }
    
    private void configurarEncabezado() {
     Encabezado1.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(217, 217, 217)));
     BarraNav.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, new Color(217, 217, 217)));
    }
    private void btnModificarInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarInsumoActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if(filaSeleccionada == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un insumo de la tabla.");
            return;
        }
        int id = (int) jTable1.getValueAt(filaSeleccionada, 0);
        Insumo ins = inventario.buscarId(id);
        if(ins!=null){
            jScrollPane1.setVisible(false);
            ModificarInsumo panel = new ModificarInsumo(this,ins);
            panel.setBounds(jScrollPane1.getBounds());
            getContentPane().add(panel);
            panel.setVisible(true);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnModificarInsumoActionPerformed

    private void btnActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarStockActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un insumo de la tabla.");
        return;
    }
    int id = (int) jTable1.getValueAt(filaSeleccionada, 0);
    Insumo ins = inventario.buscarId(id);
    if (ins != null) {
        jScrollPane1.setVisible(false);
        ActualizarStock panel = new ActualizarStock(this, ins, inventario);
        panel.setBounds(jScrollPane1.getBounds());
        getContentPane().add(panel);
        panel.setVisible(true);
        revalidate();
        repaint();
    }
    }//GEN-LAST:event_btnActualizarStockActionPerformed

    private void btnEliminarInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInsumoActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un insumo de la tabla."
            );
            return;
        }
        int id = (int) jTable1.getValueAt(filaSeleccionada, 0);
        Insumo ins = inventario.buscarId(id);
        if (ins == null) {
            javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se encontró el insumo."
            );
            return;
        }
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea eliminar el insumo \"" +
            ins.getNombre() + "\"?",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            inventario.eliminarInsumo(id);
            inventario.guardarArchivo();
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Insumo eliminado correctamente."
            );
        configurarTabla();
    }
    }//GEN-LAST:event_btnEliminarInsumoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        InventarioPantallaInicial inv = new InventarioPantallaInicial(rolUsuario, nombreUsuario);
        inv.setSize(this.getSize());
        inv.setLocation(this.getLocation());
        inv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        buscarInsumo();
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void buscarInsumo(){
    String texto = jTextField1.getText().trim();
    if (texto.isEmpty()) {
        configurarTabla();
        return;
    }
    try {
        int id = Integer.parseInt(texto);
        Insumo ins = inventario.buscarId(id);
        if (ins != null) {
            javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new String[]{"ID", "Nombre", "Unidad", "Stock", "Stock Minimo", "Precio de Compra", "Cantidad por Pizza"}, 0
            );
            modelo.addRow(new Object[]{
                ins.getId(),
                ins.getNombre(),
                ins.getUnidad(),
                String.format("%.2f", ins.getStockActual()),
                String.format("%.2f", ins.getStockMinimo()),
                String.format("%.2f", ins.getPrecioCompra()),
                String.format("%.2f", ins.getCantidadPorPizza())
            });
            jTable1.setModel(modelo);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Insumo no encontrado.");
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un ID numérico válido.");
    }
    }
    
    public void mostrarTabla(){
        configurarTabla();
        jScrollPane1.setVisible(true);
        revalidate();
        repaint();
    }
    
    private void cargarImagen(JLabel label, String ruta){
     label.setText("");
    try {
        java.io.File archivo = new java.io.File(ruta);
        if (!archivo.exists()) {
            System.err.println("Imagen no encontrada: " + ruta);
            return;
        }
        ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());
        Image imgEscalada = icono.getImage().getScaledInstance(
            label.getPreferredSize().width,
            label.getPreferredSize().height,
            Image.SCALE_SMOOTH
        );
        label.setIcon(new ImageIcon(imgEscalada));
    } catch (Exception e) {
        System.err.println("Error cargando imagen: " + e.getMessage());
    }
    }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuscarInsumos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNav;
    private javax.swing.JPanel Encabezado1;
    private javax.swing.JPanel PiePag;
    private javax.swing.JLabel Rol1;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnFinanzas;
    private javax.swing.JButton btnInvetario;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
