/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.IU;

public class CancelarVentaGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CancelarVentaGUI.class.getName());
    private String nombreUsuario;
    private String rolUsuario;
    private javax.swing.JButton btnActivo = null;
    private pizzeria.model.Venta ventaCancelar = null;
    private pizzeria.model.Reserva reservaCancelar = null;
    private boolean cancelandoReserva = false;

    /**
     * Creates new form MenuGerente
     */
    
        public CancelarVentaGUI() {
    this("Cajero", "", (pizzeria.model.Venta) null);
}

public CancelarVentaGUI(String rol, String nombre) {
    this(rol, nombre, ContextoVentasGUI.getInstancia().getVentaSeleccionadaConsulta());
}

public CancelarVentaGUI(String rol, String nombre, pizzeria.model.Venta venta) {
    initComponents();

    this.rolUsuario = rol;
    this.nombreUsuario = nombre;
    this.ventaCancelar = venta;
    this.reservaCancelar = null;
    this.cancelandoReserva = false;

    prepararVentanaCancelar();
    activarBoton(btnInicio);

    if (venta != null) {
        ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(venta);
    }

    cargarVentaSeleccionada();
}

public CancelarVentaGUI(String rol, String nombre, pizzeria.model.Reserva reserva) {
    initComponents();

    this.rolUsuario = rol;
    this.nombreUsuario = nombre;
    this.ventaCancelar = null;
    this.reservaCancelar = reserva;
    this.cancelandoReserva = true;

    prepararVentanaCancelar();
    activarBoton(btnUsuarios);

    cargarReservaSeleccionada();
}
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rol = new javax.swing.JLabel();
        BarraNav = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        Interfaz = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblClienteCancelar = new javax.swing.JLabel();
        lblEstadoCancelar = new javax.swing.JLabel();
        lblVentaCancelar = new javax.swing.JLabel();
        lblMetodoCancelar = new javax.swing.JLabel();
        lblReembolsoCancelar = new javax.swing.JLabel();
        lblTotalCancelar = new javax.swing.JLabel();
        lblDetalleCancelar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        PiePag = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        Encabezado.setBackground(new java.awt.Color(168, 27, 29));
        Encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LA CASA DEL SABOR");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("LOGO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIZZERIA");

        Rol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rol.setForeground(new java.awt.Color(255, 255, 255));
        Rol.setText("Cajero");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1149, Short.MAX_VALUE)
                .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BarraNav.setBackground(new java.awt.Color(28, 28, 28));
        BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnInicio.setBackground(new java.awt.Color(168, 27, 29));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ventas");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnUsuarios.setBackground(new java.awt.Color(28, 28, 28));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Reservas");
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnReportes.setBackground(new java.awt.Color(28, 28, 28));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Ver Menu");
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(28, 28, 28));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        Interfaz.setBackground(new java.awt.Color(255, 255, 255));
        Interfaz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(168, 27, 29));
        jLabel19.setText("CANCELAR VENTA PAGADA");

        jLabel8.setForeground(new java.awt.Color(74, 74, 74));
        jLabel8.setText("Revisa la venta antes de confirmar la cancelación y el reembolso.");

        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton3.setText("VOLVER A CONSULTAS");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(168, 27, 29));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CONFIRMAR CANCELACION");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jPanel2.setForeground(new java.awt.Color(252, 235, 235));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel3.setText("DATOS DE LA VENTA");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N

        lblClienteCancelar.setText("Cliente:");

        lblEstadoCancelar.setText("Metodo de pago:");

        lblVentaCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        lblVentaCancelar.setText("Venta N.º 001");

        lblMetodoCancelar.setText("Fecha:");

        lblReembolsoCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        lblReembolsoCancelar.setText("Reembolso:");

        lblTotalCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTotalCancelar.setText("Total pagado:");

        lblDetalleCancelar.setText("Detalle: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClienteCancelar)
                            .addComponent(jLabel3)
                            .addComponent(lblVentaCancelar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel6))
                            .addComponent(lblMetodoCancelar))
                        .addContainerGap(196, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetalleCancelar)
                            .addComponent(lblReembolsoCancelar)
                            .addComponent(lblTotalCancelar)
                            .addComponent(lblEstadoCancelar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addComponent(lblVentaCancelar)
                .addGap(29, 29, 29)
                .addComponent(lblClienteCancelar)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMetodoCancelar)
                .addGap(18, 18, 18)
                .addComponent(lblEstadoCancelar)
                .addGap(18, 18, 18)
                .addComponent(lblDetalleCancelar)
                .addGap(29, 29, 29)
                .addComponent(lblTotalCancelar)
                .addGap(18, 18, 18)
                .addComponent(lblReembolsoCancelar)
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(252, 235, 235));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel24.setForeground(new java.awt.Color(4, 74, 74));
        jLabel24.setText("Esta acción cancelará una venta ");

        jLabel25.setForeground(new java.awt.Color(4, 74, 74));
        jLabel25.setText("que ya fue registrada y pagada.");

        jLabel26.setText("Se registrará el reembolso correspondiente");

        jLabel27.setText("¿Desea continuar?  ");

        jLabel28.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(168, 27, 29));
        jLabel28.setText("ADVERTENCIA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel28)
                .addGap(37, 37, 37)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addGap(41, 41, 41)
                .addComponent(jLabel26)
                .addGap(27, 27, 27)
                .addComponent(jLabel27)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InterfazLayout = new javax.swing.GroupLayout(Interfaz);
        Interfaz.setLayout(InterfazLayout);
        InterfazLayout.setHorizontalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InterfazLayout.setVerticalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BarraNavLayout = new javax.swing.GroupLayout(BarraNav);
        BarraNav.setLayout(BarraNavLayout);
        BarraNavLayout.setHorizontalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BarraNavLayout.setVerticalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(674, Short.MAX_VALUE))
            .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PiePag.setBackground(new java.awt.Color(28, 28, 28));
        PiePag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Powered by StarTech");

        jLabel5.setText("Logo");

        javax.swing.GroupLayout PiePagLayout = new javax.swing.GroupLayout(PiePag);
        PiePag.setLayout(PiePagLayout);
        PiePagLayout.setHorizontalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PiePagLayout.setVerticalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGroup(PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(BarraNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BarraNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PiePag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
         new VentasGUI(rolUsuario, nombreUsuario).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new ConsultarReservasGUI(rolUsuario, nombreUsuario).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        PantallaMenuPublico.mostrar(this);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this, "¿Desea cerrar sesión?", "Cerrar Sesión",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        new LoginGUI().setVisible(true);
    }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if (cancelandoReserva) {
        new ConsultarReservasGUI(rolUsuario, nombreUsuario).setVisible(true);
    } else {
        new ConsultarVentasGUI(rolUsuario, nombreUsuario).setVisible(true);
    }

    this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (cancelandoReserva) {
        confirmarCancelacionReserva();
    } else {
        confirmarCancelacionVenta();
    }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void mostrarUsuario() {
    
        if (rolUsuario == null || rolUsuario.trim().isEmpty()) {
            rolUsuario = "Cajero";
        }

        if (nombreUsuario == null) {
            nombreUsuario = "";
        }

        if (nombreUsuario.trim().isEmpty()) {
            Rol.setText(rolUsuario);
        } else {
            Rol.setText(rolUsuario + ": " + nombreUsuario);
        }
    }
    
    @SuppressWarnings("unused")
    private void cargarPanel(javax.swing.JPanel panel) {
        Interfaz.removeAll();                    // limpia el contenido anterior
        Interfaz.setLayout(new java.awt.BorderLayout());
        Interfaz.add(panel, java.awt.BorderLayout.CENTER);
        Interfaz.revalidate();                   // refresca el layout
        Interfaz.repaint();                      // redibuja
    }
    private void configurarHover() {
        javax.swing.JButton[] botones = {
            btnInicio,
            btnUsuarios,
            btnReportes,
            btnCerrar
        };
    
        for (javax.swing.JButton b : botones) {
            b.setContentAreaFilled(true);
            b.setOpaque(true);
            b.setBorderPainted(false);
            b.setBackground(java.awt.Color.WHITE);
            b.setForeground(new java.awt.Color(60, 60, 60));
        
            b.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(230, 230, 230));
            b.setForeground(new java.awt.Color(168, 27, 29)); // #A81B1D
        }
    }
    @Override
    public void mouseExited(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            b.setForeground(new java.awt.Color(60, 60, 60));
        }
    }
});
        }
    }
    
    private void activarBoton(javax.swing.JButton boton) {
    // Resetea el anterior
        if (btnActivo != null) {
            btnActivo.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            btnActivo.setForeground(new java.awt.Color(60, 60, 60));
        }
        boton.setBackground(new java.awt.Color(168, 27, 29)); // #A81B1D
        boton.setForeground(new java.awt.Color(255, 255, 255)); // #FFFFFF
        btnActivo = boton;
    }
    
    private void cargarVentaSeleccionada() {
           jLabel19.setText("CANCELAR VENTA PAGADA");
    jLabel8.setText("Revisa la venta antes de confirmar la cancelación y el reembolso.");
    jLabel3.setText("DATOS DE LA VENTA");
    jLabel24.setText("Esta acción cancelará una venta");
    jLabel25.setText("que ya fue registrada y pagada.");
    jLabel26.setText("Se registrará el reembolso correspondiente");
    jLabel27.setText("¿Desea continuar?");

    pizzeria.model.Venta venta = ventaCancelar;

    if (venta == null) {
        venta = ContextoVentasGUI.getInstancia().getVentaSeleccionadaConsulta();
    }

    if (venta == null) {
        lblVentaCancelar.setText("Venta N.º -");
        lblClienteCancelar.setText("Cliente: -");
        lblMetodoCancelar.setText("Método de pago: -");
        lblEstadoCancelar.setText("Estado actual: -");
        lblTotalCancelar.setText("Total pagado: Bs. 0.00");
        lblReembolsoCancelar.setText("Reembolso: Bs. 0.00");
        lblDetalleCancelar.setText("Detalle: no se seleccionó ninguna venta");
        return;
    }

    venta.calcularTotal();

    lblVentaCancelar.setText("Venta N.º " + String.format("%03d", venta.getId()));
    lblClienteCancelar.setText("Cliente: " + obtenerClienteVisual(venta));
    lblMetodoCancelar.setText("Método de pago: " + venta.getMetodoPago());
    lblEstadoCancelar.setText("Estado actual: " + venta.getEstado());
    lblTotalCancelar.setText("Total pagado: Bs. " + String.format("%.2f", venta.getTotal()));
    lblReembolsoCancelar.setText("Reembolso: Bs. " + String.format("%.2f", venta.getTotal()));
    lblDetalleCancelar.setText("Detalle: " + obtenerDetalleVisual(venta));
        }
    
    private void cargarReservaSeleccionada() {
    jLabel19.setText("CANCELAR RESERVA");
    jLabel8.setText("Revisa la reserva antes de confirmar la cancelación y el reembolso.");
    jLabel3.setText("DATOS DE LA RESERVA");
    jLabel24.setText("Esta acción cancelará una reserva");
    jLabel25.setText("que ya fue registrada y pagada.");
    jLabel26.setText("Se registrará el reembolso correspondiente");
    jLabel27.setText("¿Desea continuar?");

    pizzeria.model.Reserva reserva = reservaCancelar;

    if (reserva == null) {
        lblVentaCancelar.setText("Reserva N.º -");
        lblClienteCancelar.setText("Cliente: -");
        lblMetodoCancelar.setText("Teléfono: -");
        lblEstadoCancelar.setText("Estado actual: -");
        lblTotalCancelar.setText("Total pagado: Bs. 0.00");
        lblReembolsoCancelar.setText("Reembolso: Bs. 0.00");
        lblDetalleCancelar.setText("Detalle: no se seleccionó ninguna reserva");
        return;
    }

    double total = reserva.calcularTotal();

    lblVentaCancelar.setText("Reserva N.º " + String.format("%03d", reserva.getId()));
    lblClienteCancelar.setText("Cliente: " + obtenerClienteReservaVisual(reserva));
    lblMetodoCancelar.setText("Teléfono: " + reserva.getTelefono());
    lblEstadoCancelar.setText("Estado actual: " + reserva.getEstado());
    lblTotalCancelar.setText("Total pagado: Bs. " + String.format("%.2f", total));
    lblReembolsoCancelar.setText("Reembolso: Bs. " + String.format("%.2f", total));
    lblDetalleCancelar.setText("Detalle: " + obtenerDetalleReservaVisual(reserva));
}
    
    private String obtenerClienteVisual(pizzeria.model.Venta venta) {
        String cliente = venta.getNombreCliente();

        if (cliente == null || cliente.trim().isEmpty()) {
            return "Sin nombre";
        }

        cliente = cliente.trim();

        try {
            Double.parseDouble(cliente);
            return "Sin nombre";
        } catch (NumberFormatException e) {
            return cliente;
        }
    }
    
    private String obtenerDetalleVisual(pizzeria.model.Venta venta) {
        StringBuilder detalle = new StringBuilder();

        for (pizzeria.model.DetalleVenta item : venta.getItems()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(item.getCantidad())
                    .append("x ")
                    .append(item.getProducto().getNombre());
        }

        for (pizzeria.model.DetalleCombo combo : venta.getCombos()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(combo.getCantidad())
                    .append("x Combo #")
                    .append(combo.getNroCombo());
        }

        if (detalle.length() == 0) {
            return "Sin detalle";
        }

        return detalle.toString();
    }
    
    private void prepararVentanaCancelar() {
    configurarVentanaCancelar();
    reconstruirEstructuraPrincipal();
    reconstruirInterfazCancelacion();
    mostrarUsuario();
    configurarHover();
}
    private void configurarVentanaCancelar() {
    setSize(1280, 720);
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setMaximumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setResizable(false);
    setLocationRelativeTo(null);

    Encabezado.setPreferredSize(new java.awt.Dimension(1280, 100));
    BarraNav.setPreferredSize(new java.awt.Dimension(280, 560));
    PiePag.setPreferredSize(new java.awt.Dimension(1280, 47));
    Interfaz.setPreferredSize(new java.awt.Dimension(1000, 560));
}
    
    private void reconstruirEstructuraPrincipal() {
    getContentPane().removeAll();

    Fondo.removeAll();
    Fondo.setLayout(new java.awt.BorderLayout());
    Fondo.setBackground(java.awt.Color.WHITE);

    BarraNav.removeAll();
    BarraNav.setLayout(new javax.swing.BoxLayout(BarraNav, javax.swing.BoxLayout.Y_AXIS));
    BarraNav.setBackground(new java.awt.Color(28, 28, 28));
    BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

    java.awt.Dimension tamBoton = new java.awt.Dimension(250, 60);

    btnInicio.setMaximumSize(tamBoton);
    btnInicio.setPreferredSize(tamBoton);
    btnUsuarios.setMaximumSize(tamBoton);
    btnUsuarios.setPreferredSize(tamBoton);
    btnReportes.setMaximumSize(tamBoton);
    btnReportes.setPreferredSize(tamBoton);
    btnCerrar.setMaximumSize(tamBoton);
    btnCerrar.setPreferredSize(tamBoton);

    btnInicio.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    btnUsuarios.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    btnReportes.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    btnCerrar.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);

    BarraNav.add(javax.swing.Box.createVerticalStrut(58));
    BarraNav.add(btnInicio);
    BarraNav.add(javax.swing.Box.createVerticalStrut(60));
    BarraNav.add(btnUsuarios);
    BarraNav.add(javax.swing.Box.createVerticalStrut(49));
    BarraNav.add(btnReportes);
    BarraNav.add(javax.swing.Box.createVerticalStrut(55));
    BarraNav.add(btnCerrar);
    BarraNav.add(javax.swing.Box.createVerticalGlue());

    javax.swing.JPanel cuerpo = new javax.swing.JPanel(new java.awt.BorderLayout());
    cuerpo.setBackground(java.awt.Color.WHITE);
    cuerpo.add(BarraNav, java.awt.BorderLayout.WEST);
    cuerpo.add(Interfaz, java.awt.BorderLayout.CENTER);

    Fondo.add(Encabezado, java.awt.BorderLayout.NORTH);
    Fondo.add(cuerpo, java.awt.BorderLayout.CENTER);
    Fondo.add(PiePag, java.awt.BorderLayout.SOUTH);

    setContentPane(Fondo);

    revalidate();
    repaint();
}
    
    private void reconstruirInterfazCancelacion() {
    Interfaz.removeAll();
    Interfaz.setLayout(new java.awt.BorderLayout(20, 20));
    Interfaz.setBackground(java.awt.Color.WHITE);
    Interfaz.setBorder(javax.swing.BorderFactory.createEmptyBorder(35, 36, 35, 36));

    javax.swing.JPanel panelSuperior = new javax.swing.JPanel();
    panelSuperior.setOpaque(false);
    panelSuperior.setLayout(new java.awt.BorderLayout());

    javax.swing.JPanel panelBotones = new javax.swing.JPanel();
    panelBotones.setOpaque(false);
    panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 110, 0));
    panelBotones.add(jButton3);
    panelBotones.add(jButton4);

    javax.swing.JPanel panelTitulos = new javax.swing.JPanel();
    panelTitulos.setOpaque(false);
    panelTitulos.setLayout(new javax.swing.BoxLayout(panelTitulos, javax.swing.BoxLayout.Y_AXIS));
    panelTitulos.add(jLabel19);
    panelTitulos.add(javax.swing.Box.createVerticalStrut(8));
    panelTitulos.add(jLabel8);

    panelSuperior.add(panelBotones, java.awt.BorderLayout.NORTH);
    panelSuperior.add(javax.swing.Box.createVerticalStrut(24), java.awt.BorderLayout.CENTER);
    panelSuperior.add(panelTitulos, java.awt.BorderLayout.SOUTH);

    jPanel2.removeAll();
    jPanel2.setBackground(java.awt.Color.WHITE);
    jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
    jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)),
            javax.swing.BorderFactory.createEmptyBorder(22, 26, 22, 26)
    ));

    jPanel2.add(jLabel3);
    jPanel2.add(javax.swing.Box.createVerticalStrut(30));
    jPanel2.add(lblVentaCancelar);
    jPanel2.add(javax.swing.Box.createVerticalStrut(20));
    jPanel2.add(lblClienteCancelar);
    jPanel2.add(javax.swing.Box.createVerticalStrut(15));
    jPanel2.add(lblMetodoCancelar);
    jPanel2.add(javax.swing.Box.createVerticalStrut(15));
    jPanel2.add(lblEstadoCancelar);
    jPanel2.add(javax.swing.Box.createVerticalStrut(15));
    jPanel2.add(lblDetalleCancelar);
    jPanel2.add(javax.swing.Box.createVerticalStrut(25));
    jPanel2.add(lblTotalCancelar);
    jPanel2.add(javax.swing.Box.createVerticalStrut(15));
    jPanel2.add(lblReembolsoCancelar);

    jPanel4.removeAll();
    jPanel4.setBackground(new java.awt.Color(252, 235, 235));
    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
    jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)),
            javax.swing.BorderFactory.createEmptyBorder(25, 39, 25, 39)
    ));

    jPanel4.add(jLabel28);
    jPanel4.add(javax.swing.Box.createVerticalStrut(35));
    jPanel4.add(jLabel24);
    jPanel4.add(javax.swing.Box.createVerticalStrut(12));
    jPanel4.add(jLabel25);
    jPanel4.add(javax.swing.Box.createVerticalStrut(40));
    jPanel4.add(jLabel26);
    jPanel4.add(javax.swing.Box.createVerticalStrut(25));
    jPanel4.add(jLabel27);

    javax.swing.JPanel panelCentral = new javax.swing.JPanel();
    panelCentral.setOpaque(false);
    panelCentral.setLayout(new java.awt.GridLayout(1, 2, 55, 0));
    panelCentral.add(jPanel2);
    panelCentral.add(jPanel4);

    Interfaz.add(panelSuperior, java.awt.BorderLayout.NORTH);
    Interfaz.add(panelCentral, java.awt.BorderLayout.CENTER);

    Interfaz.revalidate();
    Interfaz.repaint();
}
   
    private String obtenerClienteReservaVisual(pizzeria.model.Reserva reserva) {
    if (reserva == null || reserva.getNombreCliente() == null || reserva.getNombreCliente().trim().isEmpty()) {
        return "Sin nombre";
    }

    return reserva.getNombreCliente().trim();
}
    
    
    
    private String obtenerDetalleReservaVisual(pizzeria.model.Reserva reserva) {
    StringBuilder detalle = new StringBuilder();

    if (reserva == null || reserva.getPedido() == null) {
        return "Sin detalle";
    }

    for (pizzeria.model.DetalleVenta item : reserva.getPedido()) {
        if (detalle.length() > 0) {
            detalle.append(", ");
        }

        detalle.append(item.getCantidad())
                .append("x ")
                .append(item.getProducto().getNombre());
    }

    if (detalle.length() == 0) {
        return "Sin detalle";
    }

    return detalle.toString();
}
    
    private void confirmarCancelacionVenta() {
    pizzeria.model.Venta venta = ventaCancelar;

    if (venta == null) {
        venta = ContextoVentasGUI.getInstancia().getVentaSeleccionadaConsulta();
    }

    if (venta == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No hay una venta seleccionada para cancelar.",
                "Venta no seleccionada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (venta.getEstado() == pizzeria.model.EstadoPedido.ENTREGADO) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se puede cancelar una venta que ya fue entregada.",
                "Venta no cancelable",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (venta.getEstado() == pizzeria.model.EstadoPedido.CANCELADO) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Esta venta ya fue cancelada anteriormente.",
                "Venta ya cancelada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de cancelar la venta N.º "
                    + String.format("%03d", venta.getId())
                    + "?\nSe registrará un reembolso de Bs. "
                    + String.format("%.2f", venta.getTotal()) + ".",
            "Confirmar cancelación",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
    );

    if (respuesta != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    boolean cancelada = ContextoVentasGUI.getInstancia()
            .getGestorVenta()
            .cancelarVentaPagada(venta.getId());

    if (cancelada) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Venta cancelada correctamente.\nReembolso registrado: Bs. "
                        + String.format("%.2f", venta.getTotal()),
                "Cancelación exitosa",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(null);

        new ConsultarVentasGUI(rolUsuario, nombreUsuario).setVisible(true);
        this.dispose();
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se pudo cancelar la venta.\nPuede que ya esté entregada, cancelada o no exista.",
            "No se pudo cancelar",
            javax.swing.JOptionPane.WARNING_MESSAGE
    );
}
    
    private void confirmarCancelacionReserva() {
    pizzeria.model.Reserva reserva = reservaCancelar;

    if (reserva == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No hay una reserva seleccionada para cancelar.",
                "Reserva no seleccionada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (reserva.getEstado() == pizzeria.model.EstadoReserva.CANCELADA) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Esta reserva ya fue cancelada anteriormente.",
                "Reserva ya cancelada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (reserva.getEstado() == pizzeria.model.EstadoReserva.LISTA
            || reserva.getEstado() == pizzeria.model.EstadoReserva.ENTREGADA) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se puede cancelar una reserva lista o entregada.",
                "Reserva no cancelable",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de cancelar la reserva N.º "
                    + String.format("%03d", reserva.getId())
                    + "?\nSe registrará el reembolso correspondiente.",
            "Confirmar cancelación de reserva",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
    );

    if (respuesta != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    boolean cancelada = ContextoVentasGUI.getInstancia()
            .getGestorVenta()
            .cancelarReservaGUI(reserva.getId());

    if (cancelada) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Reserva cancelada correctamente.\nSe registró el reembolso correspondiente.",
                "Cancelación exitosa",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        new ConsultarReservasGUI(rolUsuario, nombreUsuario).setVisible(true);
        this.dispose();
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se pudo cancelar la reserva.\nPuede que ya esté cancelada, lista, entregada o no esté disponible.",
            "No se pudo cancelar",
            javax.swing.JOptionPane.WARNING_MESSAGE
    );
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CancelarVentaGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNav;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Interfaz;
    private javax.swing.JPanel PiePag;
    private javax.swing.JLabel Rol;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblClienteCancelar;
    private javax.swing.JLabel lblDetalleCancelar;
    private javax.swing.JLabel lblEstadoCancelar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMetodoCancelar;
    private javax.swing.JLabel lblReembolsoCancelar;
    private javax.swing.JLabel lblTotalCancelar;
    private javax.swing.JLabel lblVentaCancelar;
    // End of variables declaration//GEN-END:variables
}
