/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.IU;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class ConsultarVentasGUI extends javax.swing.JFrame {
    
    private java.util.ArrayList<pizzeria.model.Venta> ventasMostradas = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarVentasGUI.class.getName());
    private String nombreUsuario;
    private String rolUsuario;
    private javax.swing.JButton btnActivo = null;

    /**
     * Creates new form MenuGerente
     */
    public ConsultarVentasGUI() {
    initComponents();

    this.rolUsuario = "Cajero";
    this.nombreUsuario = "";

    aplicarEstructuraVisualCajero();
    reconstruirInterfazConsultarVentas();
    mostrarUsuario();

    configurarHover();
    activarBoton(btnInicio);

    cargarImagen(lblLogo, "resources/imagenes/logoCasaDelSabor.jpeg");

    configurarTablaVentas();
    cargarHistorialVentas();

    txtBuscarVentaId.addActionListener(e -> buscarVentaPorId());

    tblHistorialVentas.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            mostrarVentaSeleccionada();
        }
    });
}
    
   
    
        public ConsultarVentasGUI(String rol, String nombre) {
    initComponents();

    this.rolUsuario = rol;
    this.nombreUsuario = nombre;

    aplicarEstructuraVisualCajero();
    reconstruirInterfazConsultarVentas();
    mostrarUsuario();

    configurarHover();
    activarBoton(btnInicio);

    cargarImagen(lblLogo, "resources/imagenes/logoCasaDelSabor.jpeg");

    configurarTablaVentas();
    cargarHistorialVentas();

    txtBuscarVentaId.addActionListener(e -> buscarVentaPorId());

    tblHistorialVentas.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            mostrarVentaSeleccionada();
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rol = new javax.swing.JLabel();
        BarraNav = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        PiePag = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Interfaz = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtBuscarVentaId = new javax.swing.JTextField();
        btnBuscarVenta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorialVentas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblVentaSeleccionada = new javax.swing.JLabel();
        lblClienteSeleccionado = new javax.swing.JLabel();
        lblTotalSeleccionado = new javax.swing.JLabel();
        lblEstadoSeleccionado = new javax.swing.JLabel();
        lblDetalleSeleccionado = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        Encabezado.setBackground(new java.awt.Color(168, 27, 29));
        Encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LA CASA DEL SABOR");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("LOGO");
        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIZZERIA");

        Rol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rol.setForeground(new java.awt.Color(255, 255, 255));
        Rol.setText("Cajero");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BarraNav.setBackground(new java.awt.Color(28, 28, 28));
        BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnInicio.setBackground(new java.awt.Color(168, 27, 29));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ventas");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnUsuarios.setBackground(new java.awt.Color(28, 28, 28));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Reservas");
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnReportes.setBackground(new java.awt.Color(28, 28, 28));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Ver Menu");
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(28, 28, 28));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout BarraNavLayout = new javax.swing.GroupLayout(BarraNav);
        BarraNav.setLayout(BarraNavLayout);
        BarraNavLayout.setHorizontalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BarraNavLayout.setVerticalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PiePag.setBackground(new java.awt.Color(28, 28, 28));
        PiePag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Powered by StarTech");

        jLabel5.setText("Logo");

        javax.swing.GroupLayout PiePagLayout = new javax.swing.GroupLayout(PiePag);
        PiePag.setLayout(PiePagLayout);
        PiePagLayout.setHorizontalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PiePagLayout.setVerticalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGroup(PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        Interfaz.setBackground(new java.awt.Color(255, 255, 255));
        Interfaz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(168, 27, 29));
        jLabel19.setText("CONSULTAR VENTAS");

        jLabel8.setForeground(new java.awt.Color(74, 74, 74));
        jLabel8.setText("Busca una venta registrada o revisa el historial reciente.");

        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton3.setText("VOLVER A VENTAS");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(168, 27, 29));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CANCELAR VENTA PAGADA");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setText("Buscar por ID:");

        txtBuscarVentaId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnBuscarVenta.setForeground(new java.awt.Color(168, 27, 29));
        btnBuscarVenta.setText("BUSCAR");
        btnBuscarVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 27, 29)));
        btnBuscarVenta.addActionListener(this::btnBuscarVentaActionPerformed);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel15.setText("HISTORIAL DE VENTAS");

        tblHistorialVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "25/05/2026", "Juan Pérez", "Bs. 45", "Pendiente"},
                {"002", "25/05/2026", "Ana López", "Bs. 80", "Entregado"},
                {"003", "25/05/2026", "Sin nombre", "Bs. 35", "Entregado"},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Total", "Estado", "Metodo de Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistorialVentas.setRowHeight(25);
        jScrollPane1.setViewportView(tblHistorialVentas);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jPanel2.setForeground(new java.awt.Color(252, 235, 235));

        lblVentaSeleccionada.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblVentaSeleccionada.setText("Venta seleccionada:");

        lblClienteSeleccionado.setText("Cliente:");

        lblTotalSeleccionado.setText("Total:");

        lblEstadoSeleccionado.setText("Estado:");

        lblDetalleSeleccionado.setText("Detalle:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDetalleSeleccionado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblVentaSeleccionada)
                        .addContainerGap(601, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblClienteSeleccionado)
                        .addGap(221, 221, 221)
                        .addComponent(lblTotalSeleccionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEstadoSeleccionado)
                        .addGap(186, 186, 186))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblVentaSeleccionada)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteSeleccionado)
                    .addComponent(lblTotalSeleccionado)
                    .addComponent(lblEstadoSeleccionado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblDetalleSeleccionado)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addContainerGap(570, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InterfazLayout = new javax.swing.GroupLayout(Interfaz);
        Interfaz.setLayout(InterfazLayout);
        InterfazLayout.setHorizontalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(InterfazLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(jButton4))
                            .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8))
                            .addGroup(InterfazLayout.createSequentialGroup()
                                .addComponent(txtBuscarVentaId, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        InterfazLayout.setVerticalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarVentaId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(BarraNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarraNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PiePag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        new VentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new ConsultarReservasGUI(rolUsuario,nombreUsuario).setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FrameVerMenu ventana = new FrameVerMenu(rolUsuario, nombreUsuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this, "¿Desea cerrar sesión?", "Cerrar Sesión",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        new LoginGUI().setVisible(true);
    }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new VentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            pizzeria.model.Venta ventaSeleccionada = obtenerVentaSeleccionadaActual();

    if (ventaSeleccionada == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione una venta de la tabla antes de continuar.",
                "Venta no seleccionada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (ventaSeleccionada.getEstado() == pizzeria.model.EstadoPedido.ENTREGADO) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se puede cancelar una venta que ya fue entregada.",
                "Venta no cancelable",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (ventaSeleccionada.getEstado() == pizzeria.model.EstadoPedido.CANCELADO) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Esta venta ya fue cancelada anteriormente.",
                "Venta ya cancelada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(ventaSeleccionada);

    new CancelarVentaGUI(rolUsuario, nombreUsuario, ventaSeleccionada).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentaActionPerformed
        // TODO add your handling code here:
            buscarVentaPorId();
    }//GEN-LAST:event_btnBuscarVentaActionPerformed
    
    
    private void reconstruirInterfazConsultarVentas() {
    Interfaz.removeAll();
    Interfaz.setLayout(new java.awt.BorderLayout());
    Interfaz.setBackground(java.awt.Color.WHITE);
    Interfaz.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 35, 20, 35));

    javax.swing.JPanel panelContenido = new javax.swing.JPanel();
    panelContenido.setOpaque(false);
    panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));

    // BOTONES SUPERIORES
    javax.swing.JPanel panelBotones = new javax.swing.JPanel(new java.awt.BorderLayout());
    panelBotones.setOpaque(false);
    panelBotones.setMaximumSize(new java.awt.Dimension(760, 40));
    panelBotones.setPreferredSize(new java.awt.Dimension(760, 40));
    panelBotones.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jButton3.setPreferredSize(new java.awt.Dimension(176, 38));
    jButton4.setPreferredSize(new java.awt.Dimension(230, 38));

    panelBotones.add(jButton3, java.awt.BorderLayout.WEST);
    panelBotones.add(jButton4, java.awt.BorderLayout.EAST);

    // TÍTULOS
    jLabel19.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    jLabel8.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    // BUSCADOR
    javax.swing.JPanel panelBuscador = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 12, 0));
    panelBuscador.setOpaque(false);
    panelBuscador.setMaximumSize(new java.awt.Dimension(760, 34));
    panelBuscador.setPreferredSize(new java.awt.Dimension(760, 34));
    panelBuscador.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    txtBuscarVentaId.setPreferredSize(new java.awt.Dimension(220, 32));
    btnBuscarVenta.setPreferredSize(new java.awt.Dimension(105, 32));

    panelBuscador.add(txtBuscarVentaId);
    panelBuscador.add(btnBuscarVenta);

    jLabel14.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    reconstruirPanelHistorialVentas();

    panelContenido.add(panelBotones);
    panelContenido.add(javax.swing.Box.createVerticalStrut(18));
    panelContenido.add(jLabel19);
    panelContenido.add(javax.swing.Box.createVerticalStrut(6));
    panelContenido.add(jLabel8);
    panelContenido.add(javax.swing.Box.createVerticalStrut(18));
    panelContenido.add(jLabel14);
    panelContenido.add(javax.swing.Box.createVerticalStrut(6));
    panelContenido.add(panelBuscador);
    panelContenido.add(javax.swing.Box.createVerticalStrut(12));
    panelContenido.add(jPanel3);

    Interfaz.add(panelContenido, java.awt.BorderLayout.CENTER);

    Interfaz.revalidate();
    Interfaz.repaint();
}
    
    
    private void reconstruirPanelHistorialVentas() {
    jPanel3.removeAll();
    jPanel3.setBackground(java.awt.Color.WHITE);
    jPanel3.setBorder(null);
    jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
    jPanel3.setMaximumSize(new java.awt.Dimension(760, 285));
    jPanel3.setPreferredSize(new java.awt.Dimension(760, 285));
    jPanel3.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jLabel15.setText("HISTORIAL DE VENTAS");
    jLabel15.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jScrollPane1.setPreferredSize(new java.awt.Dimension(760, 125));
    jScrollPane1.setMaximumSize(new java.awt.Dimension(760, 125));
    jScrollPane1.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    reconstruirPanelVentaSeleccionada();

    jPanel3.add(jLabel15);
    jPanel3.add(javax.swing.Box.createVerticalStrut(8));
    jPanel3.add(jScrollPane1);
    jPanel3.add(javax.swing.Box.createVerticalStrut(10));
    jPanel3.add(jPanel2);

    jPanel3.revalidate();
    jPanel3.repaint();
}
    
    
    private void reconstruirPanelVentaSeleccionada() {
    jPanel2.removeAll();
    jPanel2.setBackground(new java.awt.Color(230, 233, 238));
    jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 20, 12, 20));
    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
    jPanel2.setMaximumSize(new java.awt.Dimension(760, 105));
    jPanel2.setPreferredSize(new java.awt.Dimension(760, 105));
    jPanel2.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    lblVentaSeleccionada.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    lblDetalleSeleccionado.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    javax.swing.JPanel filaDatos = new javax.swing.JPanel(new java.awt.GridLayout(1, 3, 18, 0));
    filaDatos.setOpaque(false);
    filaDatos.setMaximumSize(new java.awt.Dimension(720, 24));
    filaDatos.setPreferredSize(new java.awt.Dimension(720, 24));
    filaDatos.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    filaDatos.add(lblClienteSeleccionado);
    filaDatos.add(lblTotalSeleccionado);
    filaDatos.add(lblEstadoSeleccionado);

    jPanel2.add(lblVentaSeleccionada);
    jPanel2.add(javax.swing.Box.createVerticalStrut(8));
    jPanel2.add(filaDatos);
    jPanel2.add(javax.swing.Box.createVerticalStrut(8));
    jPanel2.add(lblDetalleSeleccionado);

    jPanel2.revalidate();
    jPanel2.repaint();
}
    
    
    
    private void mostrarUsuario() {
    
             if (rolUsuario == null || rolUsuario.trim().isEmpty()) {
        rolUsuario = "Cajero";
    }

    if (nombreUsuario == null) {
        nombreUsuario = "";
    }

    if (nombreUsuario.trim().isEmpty()) {
        Rol.setText(rolUsuario);
    } else {
        Rol.setText(rolUsuario + ": " + nombreUsuario);
    }

    }
    
    private void cargarPanel(javax.swing.JPanel panel) {
        Interfaz.removeAll();                    // limpia el contenido anterior
        Interfaz.setLayout(new java.awt.BorderLayout());
        Interfaz.add(panel, java.awt.BorderLayout.CENTER);
        Interfaz.revalidate();                   // refresca el layout
        Interfaz.repaint();                      // redibuja
    }
    private void configurarHover() {
        javax.swing.JButton[] botones = {
            btnInicio,
            btnUsuarios,
            btnReportes,
            btnCerrar
        };
    
        for (javax.swing.JButton b : botones) {
            b.setContentAreaFilled(true);
            b.setOpaque(true);
            b.setBorderPainted(false);
            b.setBackground(java.awt.Color.WHITE);
            b.setForeground(new java.awt.Color(60, 60, 60));
        
            b.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(230, 230, 230));
            b.setForeground(new java.awt.Color(168, 27, 29)); // #A81B1D
        }
    }
    @Override
    public void mouseExited(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            b.setForeground(new java.awt.Color(60, 60, 60));
        }
    }
});
        }
    }
    
    private void activarBoton(javax.swing.JButton boton) {
    // Resetea el anterior
        if (btnActivo != null) {
            btnActivo.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            btnActivo.setForeground(new java.awt.Color(60, 60, 60));
        }
        boton.setBackground(new java.awt.Color(168, 27, 29)); // #A81B1D
        boton.setForeground(new java.awt.Color(255, 255, 255)); // #FFFFFF
        btnActivo = boton;
    }
    
   private void cargarHistorialVentas() {
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblHistorialVentas.getModel();

    modelo.setRowCount(0);
    ventasMostradas.clear();

    java.util.ArrayList<pizzeria.model.Venta> ventas =
            ContextoVentasGUI.getInstancia()
                    .getGestorVenta()
                    .getListaVenta();

    System.out.println("Ventas cargadas en historial GUI: " + ventas.size());

    for (pizzeria.model.Venta venta : ventas) {
        ventasMostradas.add(venta);

        modelo.addRow(new Object[]{
            venta.getId(),
            obtenerClienteVisual(venta),
            "Bs. " + String.format("%.2f", venta.getTotal()),
            obtenerEstadoVentaVisual(venta),
            venta.getMetodoPago()
        });
    }

    limpiarVentaSeleccionada();
}
    
    private String obtenerClienteVisual(pizzeria.model.Venta venta) {
        String cliente = venta.getNombreCliente();

        if (cliente == null || cliente.trim().isEmpty()) {
            return "Sin nombre";
        }

        cliente = cliente.trim();

        try {
            Double.parseDouble(cliente);
            return "Sin nombre";
        } catch (NumberFormatException e) {
            return cliente;
        }
    }
    
    private void limpiarVentaSeleccionada() {
                 lblVentaSeleccionada.setText("Venta seleccionada: -");
    lblClienteSeleccionado.setText("Cliente: -");
    lblTotalSeleccionado.setText("Total: -");
    lblEstadoSeleccionado.setText("Estado: -");
    lblDetalleSeleccionado.setText("<html>Detalle: seleccione una venta de la tabla</html>");

    ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(null);
        }

    private void mostrarVentaSeleccionada() {
              int fila = tblHistorialVentas.getSelectedRow();

    if (fila == -1) {
        limpiarVentaSeleccionada();
        return;
    }

    int filaModelo = tblHistorialVentas.convertRowIndexToModel(fila);

    if (filaModelo < 0 || filaModelo >= ventasMostradas.size()) {
        limpiarVentaSeleccionada();
        return;
    }

    pizzeria.model.Venta venta = ventasMostradas.get(filaModelo);

    ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(venta);

    lblVentaSeleccionada.setText("Venta seleccionada: N.º " + String.format("%03d", venta.getId()));
    lblClienteSeleccionado.setText("Cliente: " + obtenerClienteVisual(venta));
    lblTotalSeleccionado.setText("Total: Bs. " + String.format("%.2f", venta.getTotal()));
    lblEstadoSeleccionado.setText("Estado: " + obtenerEstadoVentaVisual(venta));
    lblDetalleSeleccionado.setText("<html>Detalle: " + obtenerDetalleVisual(venta) + "</html>");

    }
    
     private String obtenerDetalleVisual(pizzeria.model.Venta venta) {
        StringBuilder detalle = new StringBuilder();

        for (pizzeria.model.DetalleVenta item : venta.getItems()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(item.getCantidad())
                    .append("x ")
                    .append(item.getProducto().getNombre());
        }

        for (pizzeria.model.DetalleCombo combo : venta.getCombos()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(combo.getCantidad())
                    .append("x Combo #")
                    .append(combo.getNroCombo());
        }

        if (detalle.length() == 0) {
            return "Sin detalle";
        }

        return detalle.toString();
    }

    private void buscarVentaPorId() {
        String texto = txtBuscarVentaId.getText().trim();

    if (texto.isEmpty()) {
        cargarHistorialVentas();
        return;
    }

    int idBuscado;

    try {
        idBuscado = Integer.parseInt(texto);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un ID de venta válido.",
                "ID inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    for (int i = 0; i < ventasMostradas.size(); i++) {
        pizzeria.model.Venta venta = ventasMostradas.get(i);

        if (venta.getId() == idBuscado) {
            tblHistorialVentas.setRowSelectionInterval(i, i);

            java.awt.Rectangle rectangulo = tblHistorialVentas.getCellRect(i, 0, true);
            tblHistorialVentas.scrollRectToVisible(rectangulo);

            mostrarVentaSeleccionada();
            return;
        }
    }

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se encontró una venta con ese ID.",
            "Venta no encontrada",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    limpiarVentaSeleccionada();
    }
    
    
    private String obtenerEstadoVentaVisual(pizzeria.model.Venta venta) {
        if (venta == null || venta.getEstado() == null) {
            return "-";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.PENDIENTE) {
            return "EN COLA DE COCINA";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.EN_PREPARACION) {
            return "EN PREPARACIÓN";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.LISTO) {
            return "LISTO PARA ENTREGAR";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.ENTREGADO) {
            return "ENTREGADO";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.CANCELADO) {
            return "CANCELADO";
        }

        return venta.getEstado().toString();
    }
    
    private void cargarImagen(JLabel label, String ruta){
        label.setText("");
       try {
           java.io.File archivo = new java.io.File(ruta);
           if (!archivo.exists()) {
               System.err.println("Imagen no encontrada: " + ruta);
               return;
           }
           ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());
           Image imgEscalada = icono.getImage().getScaledInstance(
               label.getPreferredSize().width,
               label.getPreferredSize().height,
               Image.SCALE_SMOOTH
           );
           label.setIcon(new ImageIcon(imgEscalada));
       } catch (Exception e) {
           System.err.println("Error cargando imagen: " + e.getMessage());
       }
    }
    private void configurarVentanaCajero() {
    setSize(1280, 720);
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setMaximumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setResizable(false);
    setLocationRelativeTo(null);

    Encabezado.setPreferredSize(new java.awt.Dimension(1280, 100));
    BarraNav.setPreferredSize(new java.awt.Dimension(280, 560));
    PiePag.setPreferredSize(new java.awt.Dimension(1280, 47));
}
     
    private void configurarTablaVentas() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{
                "ID", "Cliente", "Total", "Estado", "Método de Pago"
            }
    ) {
        boolean[] canEdit = new boolean[]{
            false, false, false, false, false
        };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    tblHistorialVentas.setModel(modelo);
    tblHistorialVentas.setRowHeight(25);
    tblHistorialVentas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    jLabel15.setText("HISTORIAL DE VENTAS");
}
    
    private pizzeria.model.Venta obtenerVentaSeleccionadaActual() {
    int fila = tblHistorialVentas.getSelectedRow();

    if (fila == -1) {
        return null;
    }

    int filaModelo = tblHistorialVentas.convertRowIndexToModel(fila);

    if (filaModelo < 0 || filaModelo >= ventasMostradas.size()) {
        return null;
    }

    pizzeria.model.Venta venta = ventasMostradas.get(filaModelo);

    ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(venta);

    return venta;
}
    
    private void aplicarEstructuraVisualCajero() {
    setSize(1280, 720);
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setMaximumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setResizable(false);
    setLocationRelativeTo(null);

    if (lblLogo != null) {
        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));
        lblLogo.setMinimumSize(new java.awt.Dimension(75, 75));
        lblLogo.setMaximumSize(new java.awt.Dimension(75, 75));
    }

    Encabezado.setPreferredSize(new java.awt.Dimension(1280, 100));
    Encabezado.setMinimumSize(new java.awt.Dimension(1280, 100));

    PiePag.setPreferredSize(new java.awt.Dimension(1280, 47));
    PiePag.setMinimumSize(new java.awt.Dimension(1280, 47));

    BarraNav.setPreferredSize(new java.awt.Dimension(280, 573));
    BarraNav.setMinimumSize(new java.awt.Dimension(280, 573));
    BarraNav.setMaximumSize(new java.awt.Dimension(280, 573));

    Interfaz.setPreferredSize(new java.awt.Dimension(1000, 573));
    Interfaz.setBackground(java.awt.Color.WHITE);

    reconstruirEstructuraBaseCajero();

    revalidate();
    repaint();
}
    
    private void reconstruirEstructuraBaseCajero() {
    getContentPane().removeAll();

    Fondo.removeAll();
    Fondo.setLayout(new java.awt.BorderLayout(0, 0));
    Fondo.setBackground(java.awt.Color.WHITE);

    BarraNav.removeAll();
    BarraNav.setLayout(new javax.swing.BoxLayout(BarraNav, javax.swing.BoxLayout.Y_AXIS));
    BarraNav.setBackground(new java.awt.Color(28, 28, 28));
    BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

    java.awt.Dimension tamBoton = new java.awt.Dimension(250, 60);

    configurarBotonLateral(btnInicio, tamBoton);
    configurarBotonLateral(btnUsuarios, tamBoton);
    configurarBotonLateral(btnReportes, tamBoton);
    configurarBotonLateral(btnCerrar, tamBoton);

    BarraNav.add(javax.swing.Box.createVerticalStrut(58));
    BarraNav.add(btnInicio);
    BarraNav.add(javax.swing.Box.createVerticalStrut(60));
    BarraNav.add(btnUsuarios);
    BarraNav.add(javax.swing.Box.createVerticalStrut(49));
    BarraNav.add(btnReportes);
    BarraNav.add(javax.swing.Box.createVerticalStrut(55));
    BarraNav.add(btnCerrar);
    BarraNav.add(javax.swing.Box.createVerticalGlue());

    javax.swing.JPanel cuerpo = new javax.swing.JPanel(new java.awt.BorderLayout(0, 0));
    cuerpo.setBackground(java.awt.Color.WHITE);
    cuerpo.setPreferredSize(new java.awt.Dimension(1280, 573));
    cuerpo.add(BarraNav, java.awt.BorderLayout.WEST);
    cuerpo.add(Interfaz, java.awt.BorderLayout.CENTER);

    Fondo.add(Encabezado, java.awt.BorderLayout.NORTH);
    Fondo.add(cuerpo, java.awt.BorderLayout.CENTER);
    Fondo.add(PiePag, java.awt.BorderLayout.SOUTH);

    setContentPane(Fondo);
}
    
    private void configurarBotonLateral(javax.swing.JButton boton, java.awt.Dimension tamano) {
    boton.setPreferredSize(tamano);
    boton.setMinimumSize(tamano);
    boton.setMaximumSize(tamano);
    boton.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    boton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    boton.setFocusPainted(false);
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarVentasGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNav;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Interfaz;
    private javax.swing.JPanel PiePag;
    private javax.swing.JLabel Rol;
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClienteSeleccionado;
    private javax.swing.JLabel lblDetalleSeleccionado;
    private javax.swing.JLabel lblEstadoSeleccionado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTotalSeleccionado;
    private javax.swing.JLabel lblVentaSeleccionada;
    private javax.swing.JTable tblHistorialVentas;
    private javax.swing.JTextField txtBuscarVentaId;
    // End of variables declaration//GEN-END:variables
}
