/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.IU;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class ConsultarReservasGUI extends javax.swing.JFrame {
    
    private java.util.ArrayList<pizzeria.model.Venta> ventasMostradas = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarReservasGUI.class.getName());
    private String nombreUsuario;
    private String rolUsuario;
    private javax.swing.JButton btnActivo = null;
    private java.util.List<pizzeria.model.Reserva> reservasMostradas = new java.util.ArrayList<>();
    private pizzeria.model.Reserva reservaSeleccionada = null;

    /**
     * Creates new form MenuGerente
     */
    public ConsultarReservasGUI() {
         initComponents();

        this.rolUsuario = "Cajero";
        this.nombreUsuario = "";

        configurarVentanaCajero();
        configurarTablaReservas();
        mostrarUsuario();
        reconstruirInterfazConsultarReservas();

        configurarHover();
        activarBoton(btnUsuarios);

        cargarReservas();
        cargarImagen(lblLogo, "resources/imagenes/logoCasaDelSabor.jpeg");

        txtBuscarReservaId.addActionListener(e -> buscarReservaPorId());

        tblReservas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                mostrarReservaSeleccionada();
            }
        });
    }
    
   
    
    public ConsultarReservasGUI(String rol, String nombre) {
           initComponents();

        this.rolUsuario = rol;
        this.nombreUsuario = nombre;

        configurarVentanaCajero();
        configurarTablaReservas();
        mostrarUsuario();
        reconstruirInterfazConsultarReservas();

        configurarHover();
        activarBoton(btnUsuarios);

        cargarReservas();
        cargarImagen(lblLogo, "resources/imagenes/logoCasaDelSabor.jpeg");

        txtBuscarReservaId.addActionListener(e -> buscarReservaPorId());

        tblReservas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                mostrarReservaSeleccionada();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rol = new javax.swing.JLabel();
        BarraNav = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        PiePag = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Interfaz = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtBuscarReservaId = new javax.swing.JTextField();
        btnBuscarReserva = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblReservaSeleccionada = new javax.swing.JLabel();
        lblClienteReservaSeleccionada = new javax.swing.JLabel();
        lblTelefonoReservaSeleccionada = new javax.swing.JLabel();
        lblFechaReservaSeleccionada = new javax.swing.JLabel();
        lblDetalleReservaSeleccionada = new javax.swing.JLabel();
        lblEstadoReservaSeleccionada = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        Encabezado.setBackground(new java.awt.Color(168, 27, 29));
        Encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LA CASA DEL SABOR");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("LOGO");
        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIZZERIA");

        Rol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rol.setForeground(new java.awt.Color(255, 255, 255));
        Rol.setText("Cajero");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BarraNav.setBackground(new java.awt.Color(28, 28, 28));
        BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnInicio.setBackground(new java.awt.Color(168, 27, 29));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ventas");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnUsuarios.setBackground(new java.awt.Color(28, 28, 28));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Reservas");
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnReportes.setBackground(new java.awt.Color(28, 28, 28));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Ver Menu");
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(28, 28, 28));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout BarraNavLayout = new javax.swing.GroupLayout(BarraNav);
        BarraNav.setLayout(BarraNavLayout);
        BarraNavLayout.setHorizontalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BarraNavLayout.setVerticalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PiePag.setBackground(new java.awt.Color(28, 28, 28));
        PiePag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Powered by StarTech");

        jLabel5.setText("Logo");

        javax.swing.GroupLayout PiePagLayout = new javax.swing.GroupLayout(PiePag);
        PiePag.setLayout(PiePagLayout);
        PiePagLayout.setHorizontalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PiePagLayout.setVerticalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        Interfaz.setBackground(new java.awt.Color(255, 255, 255));
        Interfaz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(168, 27, 29));
        jLabel19.setText("CONSULTAR RESERVAS");

        jLabel8.setForeground(new java.awt.Color(74, 74, 74));
        jLabel8.setText("Consulta, cancela o envía reservas a cocina.");

        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton3.setText("VOLVER A VENTAS");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(168, 27, 29));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CANCELAR RESERVA");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setText("Buscar por ID:");

        txtBuscarReservaId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnBuscarReserva.setForeground(new java.awt.Color(168, 27, 29));
        btnBuscarReserva.setText("BUSCAR");
        btnBuscarReserva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 27, 29)));
        btnBuscarReserva.addActionListener(this::btnBuscarReservaActionPerformed);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel15.setText("HISTORIAL DE VENTAS");

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "25/05/2026", "Juan Pérez", "Bs. 45", "Pendiente", null},
                {"002", "25/05/2026", "Ana López", "Bs. 80", "Entregado", null},
                {"003", "25/05/2026", "Sin nombre", "Bs. 35", "Entregado", null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Telefono", "Fecha", "Estado", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReservas.setRowHeight(25);
        jScrollPane1.setViewportView(tblReservas);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jPanel2.setForeground(new java.awt.Color(252, 235, 235));

        lblReservaSeleccionada.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblReservaSeleccionada.setText("Reserva seleccionada:");

        lblClienteReservaSeleccionada.setText("Cliente:");

        lblTelefonoReservaSeleccionada.setText("Telefono:");

        lblFechaReservaSeleccionada.setText("Fecha:");

        lblDetalleReservaSeleccionada.setText("Detalle:");

        lblEstadoReservaSeleccionada.setText("Estado:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDetalleReservaSeleccionada)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReservaSeleccionada)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblClienteReservaSeleccionada)
                                .addGap(143, 143, 143)
                                .addComponent(lblTelefonoReservaSeleccionada)
                                .addGap(124, 124, 124)
                                .addComponent(lblFechaReservaSeleccionada)
                                .addGap(135, 135, 135)
                                .addComponent(lblEstadoReservaSeleccionada)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblReservaSeleccionada)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteReservaSeleccionada)
                    .addComponent(lblTelefonoReservaSeleccionada)
                    .addComponent(lblFechaReservaSeleccionada)
                    .addComponent(lblEstadoReservaSeleccionada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblDetalleReservaSeleccionada)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addContainerGap(590, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton6.setText("ENVIAR A COCINA");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout InterfazLayout = new javax.swing.GroupLayout(Interfaz);
        Interfaz.setLayout(InterfazLayout);
        InterfazLayout.setHorizontalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(InterfazLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jButton4))
                            .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8))
                            .addGroup(InterfazLayout.createSequentialGroup()
                                .addComponent(txtBuscarReservaId, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        InterfazLayout.setVerticalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarReservaId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(BarraNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Interfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BarraNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PiePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        new VentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new ConsultarReservasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        FrameVerMenu ventana = new FrameVerMenu(rolUsuario, nombreUsuario);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this, "¿Desea cerrar sesión?", "Cerrar Sesión",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        new LoginGUI().setVisible(true);
    }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new VentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
          if (reservaSeleccionada == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione una reserva de la tabla.",
                "Reserva no seleccionada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (reservaSeleccionada.getEstado() == pizzeria.model.EstadoReserva.CANCELADA) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Esta reserva ya fue cancelada.",
                "Reserva ya cancelada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (reservaSeleccionada.getEstado() == pizzeria.model.EstadoReserva.LISTA
            || reservaSeleccionada.getEstado() == pizzeria.model.EstadoReserva.ENTREGADA) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se puede cancelar una reserva lista o entregada.",
                "Reserva no cancelable",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    new CancelarVentaGUI(rolUsuario, nombreUsuario, reservaSeleccionada).setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservaActionPerformed
        // TODO add your handling code here:
          buscarReservaPorId();
    }//GEN-LAST:event_btnBuscarReservaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
      if (reservaSeleccionada == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione una reserva de la tabla.",
                "Reserva no seleccionada",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (reservaSeleccionada.getEstado() != pizzeria.model.EstadoReserva.PENDIENTE) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Solo se pueden enviar a cocina reservas en estado PENDIENTE.",
                "Reserva no disponible",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    boolean enviada = ContextoVentasGUI.getInstancia()
            .getGestorVenta()
            .enviarReservaACocinaGUI(reservaSeleccionada.getId());

    if (enviada) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Reserva enviada a cocina correctamente.",
                "Reserva enviada",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        cargarReservas();
    } else {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se pudo enviar la reserva a cocina.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
        
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void reconstruirInterfazConsultarReservas() {
    Interfaz.removeAll();
    Interfaz.setLayout(new java.awt.BorderLayout());
    Interfaz.setBackground(java.awt.Color.WHITE);
    Interfaz.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 35, 20, 35));

    javax.swing.JPanel panelContenido = new javax.swing.JPanel();
    panelContenido.setOpaque(false);
    panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));

    javax.swing.JPanel panelBotones = new javax.swing.JPanel(new java.awt.BorderLayout());
    panelBotones.setOpaque(false);
    panelBotones.setMaximumSize(new java.awt.Dimension(780, 40));
    panelBotones.setPreferredSize(new java.awt.Dimension(780, 40));
    panelBotones.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jButton3.setPreferredSize(new java.awt.Dimension(176, 38));
    jButton6.setPreferredSize(new java.awt.Dimension(176, 38));
    jButton4.setPreferredSize(new java.awt.Dimension(190, 38));

    panelBotones.add(jButton3, java.awt.BorderLayout.WEST);
    panelBotones.add(jButton6, java.awt.BorderLayout.CENTER);
    panelBotones.add(jButton4, java.awt.BorderLayout.EAST);

    jLabel19.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    jLabel8.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    jLabel14.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    javax.swing.JPanel panelBuscador = new javax.swing.JPanel(
            new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 12, 0)
    );
    panelBuscador.setOpaque(false);
    panelBuscador.setMaximumSize(new java.awt.Dimension(780, 34));
    panelBuscador.setPreferredSize(new java.awt.Dimension(780, 34));
    panelBuscador.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    txtBuscarReservaId.setPreferredSize(new java.awt.Dimension(220, 32));
    btnBuscarReserva.setPreferredSize(new java.awt.Dimension(105, 32));

    panelBuscador.add(txtBuscarReservaId);
    panelBuscador.add(btnBuscarReserva);

    reconstruirPanelHistorialReservas();

    panelContenido.add(panelBotones);
    panelContenido.add(javax.swing.Box.createVerticalStrut(18));
    panelContenido.add(jLabel19);
    panelContenido.add(javax.swing.Box.createVerticalStrut(6));
    panelContenido.add(jLabel8);
    panelContenido.add(javax.swing.Box.createVerticalStrut(18));
    panelContenido.add(jLabel14);
    panelContenido.add(javax.swing.Box.createVerticalStrut(6));
    panelContenido.add(panelBuscador);
    panelContenido.add(javax.swing.Box.createVerticalStrut(12));
    panelContenido.add(jPanel3);

    Interfaz.add(panelContenido, java.awt.BorderLayout.CENTER);

    Interfaz.revalidate();
    Interfaz.repaint();
}
    private void reconstruirPanelHistorialReservas() {
    jPanel3.removeAll();
    jPanel3.setBackground(java.awt.Color.WHITE);
    jPanel3.setBorder(null);
    jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
    jPanel3.setMaximumSize(new java.awt.Dimension(780, 285));
    jPanel3.setPreferredSize(new java.awt.Dimension(780, 285));
    jPanel3.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jLabel15.setText("HISTORIAL DE RESERVAS");
    jLabel15.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jScrollPane1.setPreferredSize(new java.awt.Dimension(780, 125));
    jScrollPane1.setMaximumSize(new java.awt.Dimension(780, 125));
    jScrollPane1.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    reconstruirPanelReservaSeleccionada();

    jPanel3.add(jLabel15);
    jPanel3.add(javax.swing.Box.createVerticalStrut(8));
    jPanel3.add(jScrollPane1);
    jPanel3.add(javax.swing.Box.createVerticalStrut(10));
    jPanel3.add(jPanel2);

    jPanel3.revalidate();
    jPanel3.repaint();
}
    private void reconstruirPanelReservaSeleccionada() {
    jPanel2.removeAll();
    jPanel2.setBackground(new java.awt.Color(230, 233, 238));
    jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 20, 12, 20));
    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
    jPanel2.setMaximumSize(new java.awt.Dimension(780, 105));
    jPanel2.setPreferredSize(new java.awt.Dimension(780, 105));
    jPanel2.setMinimumSize(new java.awt.Dimension(780, 105));
    jPanel2.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    lblReservaSeleccionada.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    lblDetalleReservaSeleccionada.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    javax.swing.JPanel filaDatos = new javax.swing.JPanel(new java.awt.GridLayout(1, 4, 14, 0));
    filaDatos.setOpaque(false);
    filaDatos.setMaximumSize(new java.awt.Dimension(740, 24));
    filaDatos.setPreferredSize(new java.awt.Dimension(740, 24));
    filaDatos.setMinimumSize(new java.awt.Dimension(740, 24));
    filaDatos.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    filaDatos.add(lblClienteReservaSeleccionada);
    filaDatos.add(lblTelefonoReservaSeleccionada);
    filaDatos.add(lblFechaReservaSeleccionada);
    filaDatos.add(lblEstadoReservaSeleccionada);

    jPanel2.add(lblReservaSeleccionada);
    jPanel2.add(javax.swing.Box.createVerticalStrut(8));
    jPanel2.add(filaDatos);
    jPanel2.add(javax.swing.Box.createVerticalStrut(8));
    jPanel2.add(lblDetalleReservaSeleccionada);

    jPanel2.revalidate();
    jPanel2.repaint();
}
    
    private void configurarVentanaCajero() {
        setSize(1280, 720);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setLocationRelativeTo(null);

        Encabezado.setPreferredSize(new java.awt.Dimension(1280, 100));
        BarraNav.setPreferredSize(new java.awt.Dimension(280, 560));
        PiePag.setPreferredSize(new java.awt.Dimension(1280, 47));
    }
    
    private void mostrarUsuario() {
    
          if (rolUsuario == null || rolUsuario.trim().isEmpty()) {
            rolUsuario = "Cajero";
        }

        if (nombreUsuario == null) {
            nombreUsuario = "";
        }

        if (nombreUsuario.trim().isEmpty()) {
            Rol.setText(rolUsuario);
        } else {
            Rol.setText(rolUsuario + ": " + nombreUsuario);
        }
    }
    
    private void cargarPanel(javax.swing.JPanel panel) {
        Interfaz.removeAll();                    // limpia el contenido anterior
        Interfaz.setLayout(new java.awt.BorderLayout());
        Interfaz.add(panel, java.awt.BorderLayout.CENTER);
        Interfaz.revalidate();                   // refresca el layout
        Interfaz.repaint();                      // redibuja
    }
    private void configurarHover() {
        javax.swing.JButton[] botones = {
            btnInicio,
            btnUsuarios,
            btnReportes,
            btnCerrar
        };
    
        for (javax.swing.JButton b : botones) {
            b.setContentAreaFilled(true);
            b.setOpaque(true);
            b.setBorderPainted(false);
            b.setBackground(java.awt.Color.WHITE);
            b.setForeground(new java.awt.Color(60, 60, 60));
        
            b.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(230, 230, 230));
            b.setForeground(new java.awt.Color(168, 27, 29)); // #A81B1D
        }
    }
    @Override
    public void mouseExited(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            b.setForeground(new java.awt.Color(60, 60, 60));
        }
    }
});
        }
    }
    
    private void activarBoton(javax.swing.JButton boton) {
    // Resetea el anterior
        if (btnActivo != null) {
            btnActivo.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            btnActivo.setForeground(new java.awt.Color(60, 60, 60));
        }
        boton.setBackground(new java.awt.Color(168, 27, 29)); // #A81B1D
        boton.setForeground(new java.awt.Color(255, 255, 255)); // #FFFFFF
        btnActivo = boton;
    }
    
    private void cargarHistorialVentas() {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblReservas.getModel();

        modelo.setRowCount(0);
        ventasMostradas.clear();

        java.util.ArrayList<pizzeria.model.Venta> ventas =
                ContextoVentasGUI.getInstancia()
                        .getGestorVenta()
                        .getListaVenta();

        System.out.println("Ventas cargadas en historial GUI: " + ventas.size());

        for (pizzeria.model.Venta venta : ventas) {
            ventasMostradas.add(venta);

            modelo.addRow(new Object[]{
                venta.getId(),
                obtenerClienteVisual(venta),
                "Bs. " + String.format("%.2f", venta.getTotal()),
                venta.getEstado(),
                venta.getMetodoPago()
            });
        }

        limpiarVentaSeleccionada();
    }
    
    private String obtenerClienteVisual(pizzeria.model.Venta venta) {
        String cliente = venta.getNombreCliente();

        if (cliente == null || cliente.trim().isEmpty()) {
            return "Sin nombre";
        }

        cliente = cliente.trim();

        try {
            Double.parseDouble(cliente);
            return "Sin nombre";
        } catch (NumberFormatException e) {
            return cliente;
        }
    }
    
    private void limpiarVentaSeleccionada() {
            lblReservaSeleccionada.setText("Venta seleccionada: -");
            lblClienteReservaSeleccionada.setText("Cliente: -");
            lblTelefonoReservaSeleccionada.setText("Total: -");
            lblFechaReservaSeleccionada.setText("Estado: -");
            lblDetalleReservaSeleccionada.setText("Detalle: seleccione una venta de la tabla");
            
            ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(null);
        }

        private void mostrarVentaSeleccionada() {
        int fila = tblReservas.getSelectedRow();

        if (fila == -1) {
            limpiarVentaSeleccionada();
            return;
        }

        int filaModelo = tblReservas.convertRowIndexToModel(fila);

        if (filaModelo < 0 || filaModelo >= ventasMostradas.size()) {
            limpiarVentaSeleccionada();
            return;
        }

        pizzeria.model.Venta venta = ventasMostradas.get(filaModelo);
        
        ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(venta);

        lblReservaSeleccionada.setText("Venta seleccionada: N.º " + String.format("%03d", venta.getId()));
        lblClienteReservaSeleccionada.setText("Cliente: " + obtenerClienteVisual(venta));
        lblTelefonoReservaSeleccionada.setText("Total: Bs. " + String.format("%.2f", venta.getTotal()));
        lblFechaReservaSeleccionada.setText("Estado: " + venta.getEstado());
        lblDetalleReservaSeleccionada.setText("Detalle: " + obtenerDetalleVisual(venta));
    }
    
     private String obtenerDetalleVisual(pizzeria.model.Venta venta) {
        StringBuilder detalle = new StringBuilder();

        for (pizzeria.model.DetalleVenta item : venta.getItems()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(item.getCantidad())
                    .append("x ")
                    .append(item.getProducto().getNombre());
        }

        for (pizzeria.model.DetalleCombo combo : venta.getCombos()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(combo.getCantidad())
                    .append("x Combo #")
                    .append(combo.getNroCombo());
        }

        if (detalle.length() == 0) {
            return "Sin detalle";
        }

        return detalle.toString();
    }

    private void buscarVentaPorId() {
        String texto = txtBuscarReservaId.getText().trim();

        if (texto.isEmpty()) {
            cargarHistorialVentas();
            return;
        }

        int idBuscado;

        try {
            idBuscado = Integer.parseInt(texto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un ID de venta válido.",
                    "ID inválido",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        for (int i = 0; i < ventasMostradas.size(); i++) {
            pizzeria.model.Venta venta = ventasMostradas.get(i);

            if (venta.getId() == idBuscado) {
                tblReservas.setRowSelectionInterval(i, i);

                java.awt.Rectangle rectangulo = tblReservas.getCellRect(i, 0, true);
                tblReservas.scrollRectToVisible(rectangulo);

                mostrarVentaSeleccionada();
                return;
            }
        }

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró una venta con ese ID.",
                "Venta no encontrada",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        limpiarVentaSeleccionada();
    }
     
    private void cargarReservas() {
       javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblReservas.getModel();

        modelo.setRowCount(0);
        reservasMostradas.clear();
        reservaSeleccionada = null;

        java.util.List<pizzeria.model.Reserva> reservas =
                ContextoVentasGUI.getInstancia()
                        .getGestorReserva()
                        .getListaReservas();

        System.out.println("Reservas cargadas en ConsultarReservasGUI: " + reservas.size());

        for (pizzeria.model.Reserva reserva : reservas) {
            reservasMostradas.add(reserva);

            modelo.addRow(new Object[]{
                reserva.getId(),
                obtenerClienteReservaVisual(reserva),
                reserva.getTelefono(),
                reserva.getFechaReserva(),
                obtenerEstadoReservaVisual(reserva),
                "Bs. " + String.format("%.2f", reserva.calcularTotal())
            });
        }

        limpiarReservaSeleccionada();
    }
    
    private String obtenerClienteReservaVisual(pizzeria.model.Reserva reserva) {
        String cliente = reserva.getNombreCliente();

        if (cliente == null || cliente.trim().isEmpty()) {
            return "Sin nombre";
        }

        return cliente.trim();
    }
    
    private void limpiarReservaSeleccionada() {
        reservaSeleccionada = null;

    lblReservaSeleccionada.setText("Reserva seleccionada: -");
    lblClienteReservaSeleccionada.setText("Cliente: -");
    lblTelefonoReservaSeleccionada.setText("Teléfono: -");
    lblFechaReservaSeleccionada.setText("Fecha: -");
    lblEstadoReservaSeleccionada.setText("Estado: -");
    lblDetalleReservaSeleccionada.setText("<html>Detalle: seleccione una reserva</html>");
    }
    
    private void mostrarReservaSeleccionada() {
    int fila = tblReservas.getSelectedRow();

    if (fila == -1) {
        limpiarReservaSeleccionada();
        return;
    }

    int filaModelo = tblReservas.convertRowIndexToModel(fila);

    if (filaModelo < 0 || filaModelo >= reservasMostradas.size()) {
        limpiarReservaSeleccionada();
        return;
    }

    reservaSeleccionada = reservasMostradas.get(filaModelo);

    lblReservaSeleccionada.setText("Reserva seleccionada: N.º "
            + String.format("%03d", reservaSeleccionada.getId()));

    lblClienteReservaSeleccionada.setText("Cliente: "
            + obtenerClienteReservaVisual(reservaSeleccionada));

    lblTelefonoReservaSeleccionada.setText("Teléfono: "
            + textoSeguro(reservaSeleccionada.getTelefono(), "-"));

    lblFechaReservaSeleccionada.setText("Fecha: "
            + obtenerFechaReservaVisual(reservaSeleccionada));

    lblEstadoReservaSeleccionada.setText("Estado: "
            + obtenerEstadoReservaVisual(reservaSeleccionada));

    lblDetalleReservaSeleccionada.setText("<html>Detalle: "
            + obtenerDetalleReserva(reservaSeleccionada)
            + "</html>");
}
    
    
    private String textoSeguro(String valor, String defecto) {
    if (valor == null || valor.trim().isEmpty()) {
        return defecto;
    }

    return valor.trim();
}
    
    private String obtenerFechaReservaVisual(pizzeria.model.Reserva reserva) {
    if (reserva == null || reserva.getFechaReserva() == null) {
        return "-";
    }

    String fecha = reserva.getFechaReserva().toString();

    if (fecha.length() >= 16) {
        return fecha.substring(0, 16);
    }

    return fecha;
}
    
    
    private void buscarReservaPorId() {
        
         String texto = txtBuscarReservaId.getText().trim();

        if (texto.isEmpty()) {
            cargarReservas();
            return;
        }

        int idBuscado;

        try {
            idBuscado = Integer.parseInt(texto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un ID de reserva válido.",
                    "ID inválido",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        for (int i = 0; i < reservasMostradas.size(); i++) {
            pizzeria.model.Reserva reserva = reservasMostradas.get(i);

            if (reserva.getId() == idBuscado) {
                tblReservas.setRowSelectionInterval(i, i);

                java.awt.Rectangle rectangulo = tblReservas.getCellRect(i, 0, true);
                tblReservas.scrollRectToVisible(rectangulo);

                mostrarReservaSeleccionada();
                return;
            }
        }

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró una reserva con ese ID.",
                "Reserva no encontrada",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        limpiarReservaSeleccionada();
    }
    
    private String obtenerEstadoReservaVisual(pizzeria.model.Reserva reserva) {
        if (reserva == null || reserva.getEstado() == null) {
            return "-";
        }

        if (reserva.getEstado() == pizzeria.model.EstadoReserva.PENDIENTE) {
            return "PENDIENTE";
        }

        if (reserva.getEstado() == pizzeria.model.EstadoReserva.EN_COCINA) {
            return "EN COCINA";
        }

        if (reserva.getEstado() == pizzeria.model.EstadoReserva.LISTA) {
            return "LISTA PARA ENTREGAR";
        }

        if (reserva.getEstado() == pizzeria.model.EstadoReserva.ENTREGADA) {
            return "ENTREGADA";
        }

        if (reserva.getEstado() == pizzeria.model.EstadoReserva.CANCELADA) {
            return "CANCELADA";
        }

        return reserva.getEstado().toString();
    }
    
    private void cargarImagen(JLabel label, String ruta){
     label.setText("");
    try {
        java.io.File archivo = new java.io.File(ruta);
        if (!archivo.exists()) {
            System.err.println("Imagen no encontrada: " + ruta);
            return;
        }
        ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());
        Image imgEscalada = icono.getImage().getScaledInstance(
            label.getPreferredSize().width,
            label.getPreferredSize().height,
            Image.SCALE_SMOOTH
        );
        label.setIcon(new ImageIcon(imgEscalada));
    } catch (Exception e) {
        System.err.println("Error cargando imagen: " + e.getMessage());
    }
    }
    
    private void configurarTablaReservas() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "Cliente", "Teléfono", "Fecha", "Estado", "Total"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        tblReservas.setModel(modelo);
        tblReservas.setRowHeight(25);
        tblReservas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel15.setText("HISTORIAL DE RESERVAS");
    }

    private String obtenerDetalleReserva(pizzeria.model.Reserva reserva) {
        StringBuilder detalle = new StringBuilder();

        if (reserva == null || reserva.getPedido() == null) {
            return "Sin detalle";
        }

        for (pizzeria.model.DetalleVenta item : reserva.getPedido()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(item.getCantidad())
                    .append("x ")
                    .append(item.getProducto().getNombre());
        }

        if (detalle.length() == 0) {
            return "Sin detalle";
        }

        return detalle.toString();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarReservasGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNav;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Interfaz;
    private javax.swing.JPanel PiePag;
    private javax.swing.JLabel Rol;
    private javax.swing.JButton btnBuscarReserva;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClienteReservaSeleccionada;
    private javax.swing.JLabel lblDetalleReservaSeleccionada;
    private javax.swing.JLabel lblEstadoReservaSeleccionada;
    private javax.swing.JLabel lblFechaReservaSeleccionada;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblReservaSeleccionada;
    private javax.swing.JLabel lblTelefonoReservaSeleccionada;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtBuscarReservaId;
    // End of variables declaration//GEN-END:variables
}
