/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.IU;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class ConsultarVentasGUI extends javax.swing.JFrame {
    
    private java.util.ArrayList<pizzeria.model.Venta> ventasMostradas = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarVentasGUI.class.getName());
    private String nombreUsuario;
    private String rolUsuario;
    private javax.swing.JButton btnActivo = null;

    /**
     * Creates new form MenuGerente
     */
    public ConsultarVentasGUI() {
        initComponents();
        setSize(1280, 720);
        setLocationRelativeTo(null);
        Encabezado.setPreferredSize(new java.awt.Dimension(1280, 100));
        BarraNav.setPreferredSize(new java.awt.Dimension(280, 560));
        PiePag.setPreferredSize(new java.awt.Dimension(1280, 47));
        
        configurarHover();        
        activarBoton(btnInicio);
        cargarImagen(lblLogo, "resources/imagenes/logoCasaDelSabor.jpeg");
        cargarHistorialVentas();
        txtBuscarVentaId.addActionListener(e -> buscarVentaPorId());
        tblHistorialVentas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                mostrarVentaSeleccionada();
            }
        });
    }
    
   
    
    public ConsultarVentasGUI(String rol, String nombre) {
        initComponents();
        setSize(1280, 720);
        setLocationRelativeTo(null);
        Encabezado.setPreferredSize(new java.awt.Dimension(1280, 100));
        BarraNav.setPreferredSize(new java.awt.Dimension(280, 560));
        PiePag.setPreferredSize(new java.awt.Dimension(1280, 47));
        this.rolUsuario = rol;
        this.nombreUsuario = nombre;
        mostrarUsuario();
        configurarHover();        
        activarBoton(btnInicio);

        cargarHistorialVentas();
        ////por si acaso para buscar con enter en constructor con argumentos
        ///
        txtBuscarVentaId.addActionListener(e -> buscarVentaPorId());
        cargarImagen(lblLogo, "resources/imagenes/logoCasaDelSabor.jpeg");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rol = new javax.swing.JLabel();
        BarraNav = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        PiePag = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Interfaz = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtBuscarVentaId = new javax.swing.JTextField();
        btnBuscarVenta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorialVentas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblVentaSeleccionada = new javax.swing.JLabel();
        lblClienteSeleccionado = new javax.swing.JLabel();
        lblTotalSeleccionado = new javax.swing.JLabel();
        lblEstadoSeleccionado = new javax.swing.JLabel();
        lblDetalleSeleccionado = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        Encabezado.setBackground(new java.awt.Color(168, 27, 29));
        Encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LA CASA DEL SABOR");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("LOGO");
        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIZZERIA");

        Rol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rol.setForeground(new java.awt.Color(255, 255, 255));
        Rol.setText("Cajero");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BarraNav.setBackground(new java.awt.Color(28, 28, 28));
        BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnInicio.setBackground(new java.awt.Color(168, 27, 29));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ventas");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnUsuarios.setBackground(new java.awt.Color(28, 28, 28));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Reservas");
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnReportes.setBackground(new java.awt.Color(28, 28, 28));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Ver Menu");
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(28, 28, 28));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout BarraNavLayout = new javax.swing.GroupLayout(BarraNav);
        BarraNav.setLayout(BarraNavLayout);
        BarraNavLayout.setHorizontalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BarraNavLayout.setVerticalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PiePag.setBackground(new java.awt.Color(28, 28, 28));
        PiePag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Powered by StarTech");

        jLabel5.setText("Logo");

        javax.swing.GroupLayout PiePagLayout = new javax.swing.GroupLayout(PiePag);
        PiePag.setLayout(PiePagLayout);
        PiePagLayout.setHorizontalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PiePagLayout.setVerticalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGroup(PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        Interfaz.setBackground(new java.awt.Color(255, 255, 255));
        Interfaz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(168, 27, 29));
        jLabel19.setText("CONSULTAR VENTAS");

        jLabel8.setForeground(new java.awt.Color(74, 74, 74));
        jLabel8.setText("Busca una venta registrada o revisa el historial reciente.");

        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton3.setText("VOLVER A VENTAS");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(168, 27, 29));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CANCELAR VENTA PAGADA");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setText("Buscar por ID:");

        txtBuscarVentaId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnBuscarVenta.setForeground(new java.awt.Color(168, 27, 29));
        btnBuscarVenta.setText("BUSCAR");
        btnBuscarVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(168, 27, 29)));
        btnBuscarVenta.addActionListener(this::btnBuscarVentaActionPerformed);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel15.setText("HISTORIAL DE VENTAS");

        tblHistorialVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "25/05/2026", "Juan Pérez", "Bs. 45", "Pendiente"},
                {"002", "25/05/2026", "Ana López", "Bs. 80", "Entregado"},
                {"003", "25/05/2026", "Sin nombre", "Bs. 35", "Entregado"},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Total", "Estado", "Metodo de Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistorialVentas.setRowHeight(25);
        jScrollPane1.setViewportView(tblHistorialVentas);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jPanel2.setForeground(new java.awt.Color(252, 235, 235));

        lblVentaSeleccionada.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblVentaSeleccionada.setText("Venta seleccionada:");

        lblClienteSeleccionado.setText("Cliente:");

        lblTotalSeleccionado.setText("Total:");

        lblEstadoSeleccionado.setText("Estado:");

        lblDetalleSeleccionado.setText("Detalle:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDetalleSeleccionado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblVentaSeleccionada)
                        .addContainerGap(601, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblClienteSeleccionado)
                        .addGap(221, 221, 221)
                        .addComponent(lblTotalSeleccionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEstadoSeleccionado)
                        .addGap(186, 186, 186))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblVentaSeleccionada)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteSeleccionado)
                    .addComponent(lblTotalSeleccionado)
                    .addComponent(lblEstadoSeleccionado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblDetalleSeleccionado)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addContainerGap(570, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InterfazLayout = new javax.swing.GroupLayout(Interfaz);
        Interfaz.setLayout(InterfazLayout);
        InterfazLayout.setHorizontalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(InterfazLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(jButton4))
                            .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8))
                            .addGroup(InterfazLayout.createSequentialGroup()
                                .addComponent(txtBuscarVentaId, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(InterfazLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        InterfazLayout.setVerticalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarVentaId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(BarraNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarraNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PiePag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        new VentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new ConsultarReservasGUI(rolUsuario,nombreUsuario).setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FrameVerMenu ventana = new FrameVerMenu(rolUsuario, nombreUsuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this, "¿Desea cerrar sesión?", "Cerrar Sesión",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        new LoginGUI().setVisible(true);
    }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new VentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        pizzeria.model.Venta ventaSeleccionada = ContextoVentasGUI.getInstancia()
            .getVentaSeleccionadaConsulta();

        if (ventaSeleccionada == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una venta de la tabla antes de continuar.",
                    "Venta no seleccionada",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (ventaSeleccionada.getEstado() == pizzeria.model.EstadoPedido.ENTREGADO) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se puede cancelar una venta que ya fue entregada.",
                    "Venta no cancelable",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (ventaSeleccionada.getEstado() == pizzeria.model.EstadoPedido.CANCELADO) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Esta venta ya fue cancelada anteriormente.",
                    "Venta ya cancelada",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        new CancelarVentaGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentaActionPerformed
        // TODO add your handling code here:
        buscarVentaPorId();
    }//GEN-LAST:event_btnBuscarVentaActionPerformed
    
    private void mostrarUsuario() {
    
        Rol.setText(rolUsuario + ": " + nombreUsuario);
    }
    
    private void cargarPanel(javax.swing.JPanel panel) {
        Interfaz.removeAll();                    // limpia el contenido anterior
        Interfaz.setLayout(new java.awt.BorderLayout());
        Interfaz.add(panel, java.awt.BorderLayout.CENTER);
        Interfaz.revalidate();                   // refresca el layout
        Interfaz.repaint();                      // redibuja
    }
    private void configurarHover() {
        javax.swing.JButton[] botones = {
            btnInicio,
            btnUsuarios,
            btnReportes,
            btnCerrar
        };
    
        for (javax.swing.JButton b : botones) {
            b.setContentAreaFilled(true);
            b.setOpaque(true);
            b.setBorderPainted(false);
            b.setBackground(java.awt.Color.WHITE);
            b.setForeground(new java.awt.Color(60, 60, 60));
        
            b.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(230, 230, 230));
            b.setForeground(new java.awt.Color(168, 27, 29)); // #A81B1D
        }
    }
    @Override
    public void mouseExited(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            b.setForeground(new java.awt.Color(60, 60, 60));
        }
    }
});
        }
    }
    
    private void activarBoton(javax.swing.JButton boton) {
    // Resetea el anterior
        if (btnActivo != null) {
            btnActivo.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            btnActivo.setForeground(new java.awt.Color(60, 60, 60));
        }
        boton.setBackground(new java.awt.Color(168, 27, 29)); // #A81B1D
        boton.setForeground(new java.awt.Color(255, 255, 255)); // #FFFFFF
        btnActivo = boton;
    }
    
    private void cargarHistorialVentas() {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblHistorialVentas.getModel();

        modelo.setRowCount(0);
        ventasMostradas.clear();

        java.util.ArrayList<pizzeria.model.Venta> ventas =
                ContextoVentasGUI.getInstancia()
                        .getGestorVenta()
                        .getListaVenta();

        System.out.println("Ventas cargadas en historial GUI: " + ventas.size());

        for (pizzeria.model.Venta venta : ventas) {
            ventasMostradas.add(venta);

            modelo.addRow(new Object[]{
                venta.getId(),
                obtenerClienteVisual(venta),
                "Bs. " + String.format("%.2f", venta.getTotal()),
                obtenerEstadoVentaVisual(venta),
                venta.getMetodoPago()
            });
        }

        limpiarVentaSeleccionada();
    }
    
    private String obtenerClienteVisual(pizzeria.model.Venta venta) {
        String cliente = venta.getNombreCliente();

        if (cliente == null || cliente.trim().isEmpty()) {
            return "Sin nombre";
        }

        cliente = cliente.trim();

        try {
            Double.parseDouble(cliente);
            return "Sin nombre";
        } catch (NumberFormatException e) {
            return cliente;
        }
    }
    
    private void limpiarVentaSeleccionada() {
            lblVentaSeleccionada.setText("Venta seleccionada: -");
            lblClienteSeleccionado.setText("Cliente: -");
            lblTotalSeleccionado.setText("Total: -");
            lblEstadoSeleccionado.setText("Estado: -");
            lblDetalleSeleccionado.setText("Detalle: seleccione una venta de la tabla");
            
            ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(null);
        }

        private void mostrarVentaSeleccionada() {
            int fila = tblHistorialVentas.getSelectedRow();

            if (fila == -1) {
                limpiarVentaSeleccionada();
                return;
            }

            int filaModelo = tblHistorialVentas.convertRowIndexToModel(fila);

            if (filaModelo < 0 || filaModelo >= ventasMostradas.size()) {
                limpiarVentaSeleccionada();
                return;
            }

            pizzeria.model.Venta venta = ventasMostradas.get(filaModelo);

            ContextoVentasGUI.getInstancia().setVentaSeleccionadaConsulta(venta);

            lblVentaSeleccionada.setText("Venta seleccionada: N.º " + String.format("%03d", venta.getId()));
            lblClienteSeleccionado.setText("Cliente: " + obtenerClienteVisual(venta));
            lblTotalSeleccionado.setText("Total: Bs. " + String.format("%.2f", venta.getTotal()));
            lblEstadoSeleccionado.setText("Estado: " + obtenerEstadoVentaVisual(venta));
            lblDetalleSeleccionado.setText("Detalle: " + obtenerDetalleVisual(venta));
        }
    
     private String obtenerDetalleVisual(pizzeria.model.Venta venta) {
        StringBuilder detalle = new StringBuilder();

        for (pizzeria.model.DetalleVenta item : venta.getItems()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(item.getCantidad())
                    .append("x ")
                    .append(item.getProducto().getNombre());
        }

        for (pizzeria.model.DetalleCombo combo : venta.getCombos()) {
            if (detalle.length() > 0) {
                detalle.append(", ");
            }

            detalle.append(combo.getCantidad())
                    .append("x Combo #")
                    .append(combo.getNroCombo());
        }

        if (detalle.length() == 0) {
            return "Sin detalle";
        }

        return detalle.toString();
    }

    private void buscarVentaPorId() {
        String texto = txtBuscarVentaId.getText().trim();

        if (texto.isEmpty()) {
            cargarHistorialVentas();
            return;
        }

        int idBuscado;

        try {
            idBuscado = Integer.parseInt(texto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un ID de venta válido.",
                    "ID inválido",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        for (int i = 0; i < ventasMostradas.size(); i++) {
            pizzeria.model.Venta venta = ventasMostradas.get(i);

            if (venta.getId() == idBuscado) {
                tblHistorialVentas.setRowSelectionInterval(i, i);

                java.awt.Rectangle rectangulo = tblHistorialVentas.getCellRect(i, 0, true);
                tblHistorialVentas.scrollRectToVisible(rectangulo);

                mostrarVentaSeleccionada();
                return;
            }
        }

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró una venta con ese ID.",
                "Venta no encontrada",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        limpiarVentaSeleccionada();
    }
    
    
    private String obtenerEstadoVentaVisual(pizzeria.model.Venta venta) {
        if (venta == null || venta.getEstado() == null) {
            return "-";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.PENDIENTE) {
            return "EN COLA DE COCINA";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.EN_PREPARACION) {
            return "EN PREPARACIÓN";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.LISTO) {
            return "LISTO PARA ENTREGAR";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.ENTREGADO) {
            return "ENTREGADO";
        }

        if (venta.getEstado() == pizzeria.model.EstadoPedido.CANCELADO) {
            return "CANCELADO";
        }

        return venta.getEstado().toString();
    }
    
    private void cargarImagen(JLabel label, String ruta){
     label.setText("");
    try {
        java.io.File archivo = new java.io.File(ruta);
        if (!archivo.exists()) {
            System.err.println("Imagen no encontrada: " + ruta);
            return;
        }
        ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());
        Image imgEscalada = icono.getImage().getScaledInstance(
            label.getPreferredSize().width,
            label.getPreferredSize().height,
            Image.SCALE_SMOOTH
        );
        label.setIcon(new ImageIcon(imgEscalada));
    } catch (Exception e) {
        System.err.println("Error cargando imagen: " + e.getMessage());
    }
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarVentasGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNav;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Interfaz;
    private javax.swing.JPanel PiePag;
    private javax.swing.JLabel Rol;
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClienteSeleccionado;
    private javax.swing.JLabel lblDetalleSeleccionado;
    private javax.swing.JLabel lblEstadoSeleccionado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTotalSeleccionado;
    private javax.swing.JLabel lblVentaSeleccionada;
    private javax.swing.JTable tblHistorialVentas;
    private javax.swing.JTextField txtBuscarVentaId;
    // End of variables declaration//GEN-END:variables
}
