/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pizzeria.IU;
import pizzeria.model.Inventario;
import pizzeria.model.Insumo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author BENJAMIN
 */
public class InsumosBajoStock extends javax.swing.JPanel {
    private InventarioPantallaInicial padre;
    private final Inventario inventario = new Inventario();
    /**
     * Creates new form InsumosBajoStock
     */
    public InsumosBajoStock(InventarioPantallaInicial padre) {
        initComponents();
        this.padre = padre;
        inventario.cargarArchivo();
        cargarTabla();
        configurarEstiloTabla();
        btnMenu.setVisible(true);
        btnFinanzas1.setVisible(true);
        setPreferredSize(new java.awt.Dimension(980, 500));
    }
    private void cargarTabla() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new String[]{"ID", "Nombre", "Unidad", "Stock", "Stock Minimo", "Precio de Compra", "Cantidad por Pizza"}, 0
    ){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    for (Insumo ins : inventario.getInsumos()) {
        if (ins.stockBajo()) {
            modelo.addRow(new Object[]{
                ins.getId(),
                ins.getNombre(),
                ins.getUnidad(),
                String.format("%.2f", ins.getStockActual()),
                String.format("%.2f", ins.getStockMinimo()),
                String.format("%.2f", ins.getPrecioCompra()),
                String.format("%.2f", ins.getCantidadPorPizza())
            });
        }
    }
    jTable1.setModel(modelo);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnFinanzas1 = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(168, 27, 29));
        jLabel1.setText("INSUMOS CON BAJO STOCK");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnFinanzas1.setBackground(new java.awt.Color(168, 27, 29));
        btnFinanzas1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFinanzas1.setForeground(new java.awt.Color(255, 255, 255));
        btnFinanzas1.setText("Atrás");
        btnFinanzas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanzas1.addActionListener(this::btnAtrasActionPerformed);

        btnMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Actualizar Stock");
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenu.addActionListener(this::btnMenubtnActualizarStockActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1)
                        .addGap(0, 322, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFinanzas1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinanzas1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        padre.mostrarTabla();
        padre.getContentPane().remove(this);
        padre.revalidate();
        padre.repaint();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnMenubtnActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenubtnActualizarStockActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un insumo de la tabla.");
        return;
    }
        int id = (int) jTable1.getValueAt(filaSeleccionada, 0);
        Insumo ins = inventario.buscarId(id);
        if (ins != null) {
            jScrollPane1.setVisible(false);
            btnMenu.setVisible(false);
            btnFinanzas1.setVisible(false);
            ActualizarStock panel = new ActualizarStock(this, ins, inventario);
            panel.setBounds(0, 0, getWidth(), getHeight());
            add(panel);
            panel.setVisible(true);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnMenubtnActualizarStockActionPerformed

    public void mostrarTabla(){
        java.awt.Component[] componentes = getComponents();
        for (java.awt.Component c : componentes) {
            if (c instanceof ActualizarStock) {
            remove(c);
        }
    }
        jScrollPane1.setVisible(true);
        btnMenu.setVisible(true);
        btnFinanzas1.setVisible(true);
        revalidate();
        repaint();
    }

    private void configurarEstiloTabla() {
    jTable1.getTableHeader().setBackground(new Color(168, 27, 29));
    jTable1.getTableHeader().setForeground(Color.BLACK);
    jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
    jTable1.getTableHeader().setPreferredSize(new Dimension(0, 35));

    jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(
            javax.swing.JTable table, Object value, boolean isSelected,
            boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if (isSelected) {
                setBackground(new Color(168, 27, 29));
                setForeground(Color.WHITE);
            } else if (row % 2 == 0) {
                setBackground(new Color(245, 245, 245));
                setForeground(Color.BLACK);
            } else {
                setBackground(Color.WHITE);
                setForeground(Color.BLACK);
            }
            setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 5));
            return this;
        }
        });

        jTable1.setRowHeight(30);
        jTable1.setShowGrid(false);
        jTable1.setIntercellSpacing(new Dimension(0, 0));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinanzas1;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
