/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pizzeria.IU;

/**
 *
 * @author KATANA
 */
import java.awt.BorderLayout;
import java.util.ArrayList;
import pizzeria.model.Combo;
import pizzeria.model.Menu;
import pizzeria.model.Producto;
import pizzeria.model.Inventario;
import pizzeria.util.ArchivoMenu;
import javax.swing.JPanel;

public class PModificarCombos extends javax.swing.JPanel {

    private Menu menu;
    private ArchivoMenu archivoMenu;
    private JPanel interfaz;
    private Combo comboAEditar;
    private Inventario inventario;
    private ArrayList<Producto> productosEnCombo = new ArrayList<>();
    
    public PModificarCombos() {
        initComponents();
    }
    
     public PModificarCombos(JPanel interfaz, Menu menu, ArchivoMenu archivoMenu, Combo comboAEditar, Inventario inventario) {
        this.interfaz      = interfaz;
        this.menu          = menu;
        this.archivoMenu   = archivoMenu;
        this.comboAEditar  = comboAEditar;
        this.inventario = inventario;
 
        initComponents();
        configurarRadioButtons();
        cargarProductosDisponibles();  // llena jTable1 con todos los productos del menú
        precargarDatos();              // llena jTable2 y precio con los datos actuales del combo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PrecioSug = new javax.swing.JRadioButton();
        PrecioEsp = new javax.swing.JRadioButton();
        PrecioE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(168, 27, 29));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFICAR COMBO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(168, 27, 29));
        jLabel2.setText("Productos Disponibles:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Precio:");

        PrecioSug.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PrecioSug.setText("Precio Sugerido");

        PrecioEsp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PrecioEsp.setText("Precio Especial");

        PrecioE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PrecioE.setText("120");
        PrecioE.addActionListener(this::PrecioEActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(168, 27, 29));
        jLabel3.setText("Productos en el combo actualmente:");

        btnAgregar.setBackground(new java.awt.Color(168, 27, 29));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar al Combo");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(168, 27, 29));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar del Combo");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID ", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Producto"
            }
        ));
        jTable2.setRowHeight(40);
        jScrollPane2.setViewportView(jTable2);

        btnGuardar.setBackground(new java.awt.Color(168, 27, 29));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar Combo");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(106, 68, 68));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecioSug, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PrecioEsp)
                                .addGap(18, 18, 18)
                                .addComponent(PrecioE, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioSug)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrecioEsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrecioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PrecioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioEActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleccione un producto de la lista.",
                "Sin selección", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Producto seleccionado = menu.getProductos().get(fila);

        

        productosEnCombo.add(seleccionado);
        refrescarTablaCombo();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = jTable2.getSelectedRow();
        if (fila < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleccione un producto de la lista del combo.",
                "Sin selección", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        productosEnCombo.remove(fila);
        refrescarTablaCombo();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (productosEnCombo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El combo debe tener al menos un producto.",
                "Combo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        // Validar precio
        double precio;
        try {
            precio = Double.parseDouble(PrecioE.getText().trim().replace(",", "."));
            if (precio < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ingrese un precio válido (número positivo).",
                "Precio inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        // Aplicar cambios con los setters de Combo
        comboAEditar.setCombo(productosEnCombo);
        comboAEditar.setPrecio(precio);
 
        // Persistir en disco
        if (archivoMenu != null) {
            archivoMenu.guardarCombos(menu.getCombos());
        }
 
        javax.swing.JOptionPane.showMessageDialog(this,
            "Combo #" + comboAEditar.getNroCombo() + " modificado correctamente.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
 
        cargarPanel(new PVerCombos(interfaz, menu, archivoMenu, inventario));
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Descartar los cambios?",
            "Cancelar", javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE);
 
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            cargarPanel(new PVerCombos(interfaz, menu, archivoMenu, inventario));
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

private void cargarPanel(JPanel panel) {
        interfaz.removeAll();
        interfaz.setLayout(new BorderLayout());
        interfaz.add(panel, BorderLayout.CENTER);
        interfaz.revalidate();
        interfaz.repaint();
}

private void precargarDatos() {
        if (comboAEditar == null) return;
 
        // Copia de trabajo de los productos actuales del combo
        productosEnCombo = new ArrayList<>(comboAEditar.getCombo());
 
        // Precio
        double precio = comboAEditar.getPrecio();
        double sugerido = calcularPrecioSugerido();
 
        if (precio == sugerido) {
            PrecioSug.setSelected(true);
            PrecioE.setText(String.format("%.2f", sugerido));
            PrecioE.setEnabled(false);
        } else {
            PrecioEsp.setSelected(true);
            PrecioE.setText(String.format("%.2f", precio));
            PrecioE.setEnabled(true);
        }
 
        refrescarTablaCombo();
}

private double calcularPrecioSugerido() {
        double total = 0;
        for (Producto p : productosEnCombo) total += p.getPrecio();
        return total;
}

 private void cargarProductosDisponibles() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
 
        if (menu == null) return;
        for (Producto p : menu.getProductos()) {
            model.addRow(new Object[]{
                p.getID(),
                p.getNombre(),
                String.format("%.2f", p.getPrecio())
            });
        }
    }
 
  private void refrescarTablaCombo() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
 
        for (Producto p : productosEnCombo) {
            model.addRow(new Object[]{ p.getID(), p.getNombre() });
        }
 
        // Si PrecioSug está activo, actualiza el campo con el nuevo total
        if (PrecioSug.isSelected()) {
            PrecioE.setText(String.format("%.2f", calcularPrecioSugerido()));
        }
    }
  
   private void configurarRadioButtons() {
        javax.swing.ButtonGroup grupo = new javax.swing.ButtonGroup();
        grupo.add(PrecioSug);
        grupo.add(PrecioEsp);
 
        PrecioSug.addActionListener(e -> {
            PrecioE.setText(String.format("%.2f", calcularPrecioSugerido()));
            PrecioE.setEnabled(false);
        });
        PrecioEsp.addActionListener(e -> {
            PrecioE.setEnabled(true);
            PrecioE.requestFocus();
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PrecioE;
    private javax.swing.JRadioButton PrecioEsp;
    private javax.swing.JRadioButton PrecioSug;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
