/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pizzeria.IU;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.BoxLayout;
import pizzeria.model.Inventario;
import pizzeria.model.Menu;
import pizzeria.model.Producto;
import pizzeria.model.TipoProducto;
import pizzeria.util.ArchivoMenu;
import pizzeria.model.Insumo;

/**
 *
 * @author KATANA
 */
public class PModificarProducto extends javax.swing.JPanel {
    private ArrayList<JCheckBox> checkboxesInsumos = new ArrayList<>(); 
    private Inventario inventario;
    private Menu menu;
    private ArchivoMenu archivoMenu;
    private Producto productoAEditar;
    private JPanel interfaz;
    /**
     * Creates new form PModificarProducto
     */
    public PModificarProducto() {
        initComponents();
    }
    
    public PModificarProducto(JPanel interfaz, Menu menu, Inventario inventario,
                               ArchivoMenu archivoMenu, Producto producto) {
    

        this.interfaz = interfaz;
        this.menu = menu;
        this.inventario = inventario;
        this.archivoMenu = archivoMenu;
        this.productoAEditar = producto;

        initComponents();
        cargarInsumos();         
        precargarDatos();
        
    }
    
    private void precargarDatos() {
        if (productoAEditar == null) return;
 
        txtNombre.setText(productoAEditar.getNombre());
        txtPrecio.setText(String.valueOf(productoAEditar.getPrecio()));
        txtDescrip.setText(productoAEditar.getDescripcion());
 
        // Seleccionar el tipo en el combo
        String tipoStr = productoAEditar.getTipo().toString();
        for (int i = 0; i < tipoP.getItemCount(); i++) {
            if (tipoP.getItemAt(i).equalsIgnoreCase(tipoStr)) {
                tipoP.setSelectedIndex(i);
                break;
            }
        }
 
        // Marcar los checkboxes de ingredientes que ya tiene el producto
        ArrayList<Integer> idsIngredientes = productoAEditar.getIngredientes();
        for (int i = 0; i < checkboxesInsumos.size(); i++) {
            Insumo ins = inventario.getInsumos().get(i);
            checkboxesInsumos.get(i).setSelected(idsIngredientes.contains(ins.getId()));
        }
    }
    
    private void cargarInsumos() {
        panelInsumos.removeAll();
        checkboxesInsumos.clear();
        panelInsumos.setLayout(new BoxLayout(panelInsumos, BoxLayout.Y_AXIS));
 
        if (inventario != null) {
            for (Insumo ins : inventario.getInsumos()) {
                JCheckBox chk = new JCheckBox(ins.getNombre());
                chk.setBackground(java.awt.Color.WHITE);
                chk.setFont(new java.awt.Font("Segoe UI", 0, 16));
                checkboxesInsumos.add(chk);
                panelInsumos.add(chk);
            }
        }
 
        panelInsumos.revalidate();
        panelInsumos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipoP = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelInsumos = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(168, 27, 29));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFICAR PRODUCTO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre del Producto:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Precio:");

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descripción:");

        txtDescrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tipo de Producto:");

        tipoP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tipoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto", "Refresco" }));
        tipoP.addActionListener(this::tipoPActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(168, 27, 29));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(106, 68, 68));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        panelInsumos.setBackground(new java.awt.Color(255, 255, 255));

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jCheckBox3.setText("jCheckBox3");

        jCheckBox4.setText("jCheckBox4");

        javax.swing.GroupLayout panelInsumosLayout = new javax.swing.GroupLayout(panelInsumos);
        panelInsumos.setLayout(panelInsumosLayout);
        panelInsumosLayout.setHorizontalGroup(
            panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsumosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        panelInsumosLayout.setVerticalGroup(
            panelInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsumosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelInsumos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tipoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // 1. Validar nombre
        String nombre = txtNombre.getText().trim();
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ingrese el nombre del producto.",
                "Campo vacío", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        Producto existente = menu.buscarProductoNombre(nombre);
        if (existente != null && existente.getID() != productoAEditar.getID()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ya existe un producto con ese nombre.",
                    "Producto ya existe", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
 
        // 2. Validar precio
        String precioTxt = txtPrecio.getText().trim();
        double precio;
        try {
            precio = Double.parseDouble(precioTxt);
            if (precio < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ingrese un precio válido (número positivo).",
                "Precio inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        // 3. Descripción
        String descripcion = txtDescrip.getText().trim();
 
        // 4. Tipo
        TipoProducto tipo = TipoProducto.fromString((String) tipoP.getSelectedItem());
 
        // 5. Ingredientes seleccionados
        ArrayList<Integer> nuevosIngredientes = new ArrayList<>();
        for (int i = 0; i < checkboxesInsumos.size(); i++) {
            if (checkboxesInsumos.get(i).isSelected()) {
                Insumo ins = inventario.getInsumos().get(i);
                nuevosIngredientes.add(ins.getId());
            }
        }
 
        // 6. Aplicar cambios con los setters de Producto
        productoAEditar.setNombre(nombre);
        productoAEditar.setDescripcion(descripcion);
        productoAEditar.setPrecio(precio);
        productoAEditar.setTipo(tipo);
        productoAEditar.setIngredientes(nuevosIngredientes);
 
        // 7. Persistir en disco
        if (archivoMenu != null) {
            archivoMenu.guardarProductos(menu.getProductos());
        }
 
        // 8. Confirmar y volver
        javax.swing.JOptionPane.showMessageDialog(this,
            "Producto \"" + nombre + "\" modificado correctamente.",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
 
        cargarPanel(new PVerProductos(interfaz, menu, archivoMenu, inventario));        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Descartar los cambios?",
            "Cancelar", javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE);
 
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            cargarPanel(new PVerProductos(interfaz, menu, archivoMenu, inventario));
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    
     
    private void cargarPanel(JPanel panel) {
        interfaz.removeAll();
        interfaz.setLayout(new BorderLayout());
        interfaz.add(panel, BorderLayout.CENTER);
        interfaz.revalidate();
        interfaz.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInsumos;
    private javax.swing.JComboBox<String> tipoP;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
