/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pizzeria.IU;
import javax.swing.JOptionPane;

import java.util.ArrayList;
import pizzeria.model.Menu;
import pizzeria.model.Inventario;
import pizzeria.model.Insumo;
import pizzeria.util.ArchivoMenu;
import pizzeria.model.Producto;
import pizzeria.model.TipoProducto;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import javax.swing.JPanel;
/**
 *
 * @author KATANA
     */
public class PVerProductos extends javax.swing.JPanel {
    private javax.swing.JButton btnActivo = null;
    private Menu menu;
    private ArchivoMenu archivoMenu;
    private Inventario inventario;
    private JPanel interfaz;
   
    public PVerProductos() {
        initComponents();
    }

    public PVerProductos(JPanel interfaz, Menu menu, ArchivoMenu archivoMenu, Inventario inventario) {
    initComponents(); 
    this.interfaz = interfaz;    
    this.menu          = menu;
    this.archivoMenu   = archivoMenu;
    this.inventario = inventario;
    //this.inventario    = inventario;
     inventario.cargarArchivo();
    
    // Cargar tabla al abrir
    cargarTablaProductos();
    configurarPlaceholder();
 
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregarP = new javax.swing.JButton();
        btnEliminarP = new javax.swing.JButton();
        btnAgregarI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(168, 27, 29));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionar Productos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        idBuscar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idBuscar.setForeground(new java.awt.Color(217, 217, 217));

        btnBuscar.setBackground(new java.awt.Color(168, 27, 29));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnAgregarP.setBackground(new java.awt.Color(168, 27, 29));
        btnAgregarP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarP.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarP.setText("Agregar Producto");
        btnAgregarP.addActionListener(this::btnAgregarPActionPerformed);

        btnEliminarP.setBackground(new java.awt.Color(168, 27, 29));
        btnEliminarP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEliminarP.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarP.setText("Eliminar Producto");
        btnEliminarP.addActionListener(this::btnEliminarPActionPerformed);

        btnAgregarI.setBackground(new java.awt.Color(168, 27, 29));
        btnAgregarI.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarI.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarI.setText("Agregar Ingrediente ");
        btnAgregarI.addActionListener(this::btnAgregarIActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(217, 217, 217));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Descripción", "Ingredientes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizzas", "Refrescos" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        btnFiltrar.setBackground(new java.awt.Color(168, 27, 29));
        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(this::btnFiltrarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(168, 27, 29));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar Producto");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(335, 335, 335))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAgregarI, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(266, 266, 266)))
                    .addGap(7, 7, 7)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String texto = idBuscar.getText().trim();
    
    if (texto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Ingrese un nombre para buscar."
        );
        return;
    }

    ArrayList<Producto> resultados = menu.buscarProductosPorNombre(texto);
    
    if (resultados.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se encontró ningún producto con ese nombre."
        );
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);
    
    for (Producto p : resultados) {
        modelo.addRow(new Object[]{
            p.getID(),
            p.getNombre(),
            String.format("%.2f", p.getPrecio()),
            p.getDescripcion(), "xd"
        });
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        MenuAgregarProducto panel = new MenuAgregarProducto(interfaz,
        menu, inventario, archivoMenu);
        cargarPanel(panel);
        
    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed
        int fila = jTable1.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this,
                "Seleccione un producto de la tabla.");
        return;
    }

    int id = (int) jTable1.getValueAt(fila, 0);
    String nombre = jTable1.getValueAt(fila, 1).toString();

    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea eliminar el producto \"" + nombre + "\"?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

    if (opcion == JOptionPane.YES_OPTION) {

        if (menu.eliminarProducto(id)) {

            if (archivoMenu != null) {
                archivoMenu.guardarProductos(menu.getProductos());
            }

            cargarTablaProductos();

            JOptionPane.showMessageDialog(this,
                    "Producto eliminado correctamente.");
        }
    }
    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void btnAgregarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un producto de la tabla.");
            return;
        }

        int idProducto = (int) jTable1.getValueAt(fila, 0);

        Producto producto = menu.buscarProducto(idProducto);

        if (producto == null) {
            javax.swing.JOptionPane.showMessageDialog(
                 this,
                "No se encontró el producto.");
        return;
        }

         PAgregarIngrediente panel = new PAgregarIngrediente(
            interfaz,
            menu,
            inventario,
            archivoMenu,
            producto
        );

        cargarPanel(panel);
    }//GEN-LAST:event_btnAgregarIActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
         String seleccion = (String) jComboBox1.getSelectedItem();
    
    // Convertir el String del combo al enum correspondiente
        TipoProducto tipoBuscado;
        switch (seleccion) {
            case "Pizzas":    tipoBuscado = TipoProducto.PRODUCTO;    break;
            case "Refrescos": tipoBuscado = TipoProducto.REFRESCO; break;
            default:          cargarTablaProductos(); return; // si hubiera un "Todos"
        }
    
        filtrarTablaProductos(tipoBuscado);        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un producto de la tabla.");
            return;
        }

        int idProducto = (int) jTable1.getValueAt(fila, 0);

        Producto producto = menu.buscarProducto(idProducto);

        if (producto == null) {
            javax.swing.JOptionPane.showMessageDialog(
                 this,
                "No se encontró el producto.");
        return;
        }

         PModificarProducto panel = new PModificarProducto(
            interfaz,
            menu,
            inventario,
            archivoMenu,
            producto
        );

        cargarPanel(panel);
    }//GEN-LAST:event_btnModificarActionPerformed

    
    private void filtrarTablaProductos(TipoProducto tipo) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (Producto p : menu.getProductos()) {
            if (p.getTipo() != tipo) continue;

            modelo.addRow(new Object[]{
                p.getID(),
                p.getNombre(),
                String.format("%.2f", p.getPrecio()),
                p.getDescripcion(),
                construirIngredientes(p)
            });
        }
    }
    
    private String construirIngredientes(Producto p) {
        if (p.getIngredientes() == null || p.getIngredientes().isEmpty()) {
            return "(ninguno)";
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < p.getIngredientes().size(); i++) {
            int idIng = p.getIngredientes().get(i);
            Insumo ins = (inventario != null) ? inventario.buscarId(idIng) : null;
            sb.append(ins != null ? ins.getNombre() : "ID " + idIng);
            if (i < p.getIngredientes().size() - 1) sb.append(", ");
        }
        return sb.toString();
    }
    
    private void cargarPanel(JPanel panel) {
    interfaz.removeAll();
    interfaz.setLayout(new BorderLayout());
    interfaz.add(panel, BorderLayout.CENTER);
    interfaz.revalidate();
    interfaz.repaint();
}
    
    private void cargarTablaProductos(){
     DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);

    for (Producto p : menu.getProductos()) {
        modelo.addRow(new Object[]{
            p.getID(),
            p.getNombre(),
            String.format("%.2f", p.getPrecio()),
            p.getDescripcion(),
            construirIngredientes(p)   // ← reutiliza el helper
        });
    }

        jTable1.setModel(modelo);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(280);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(280);
    }   
    
    private void configurarPlaceholder() {
        idBuscar.setText("Ingrese el producto:");
        idBuscar.setForeground(java.awt.Color.GRAY);

        idBuscar.addFocusListener(new java.awt.event.FocusAdapter() {

    @Override
    public void focusGained(java.awt.event.FocusEvent e) {
        if (idBuscar.getText().equals("Ingrese el producto:")) {
            idBuscar.setText("");
            idBuscar.setForeground(new java.awt.Color(0,0,0));
        }
    }

    @Override
    public void focusLost(java.awt.event.FocusEvent e) {
        if (idBuscar.getText().trim().isEmpty()) {
            idBuscar.setText("Ingrese el producto:");
            idBuscar.setForeground(new java.awt.Color(217,217,217));
        }
    }
});// código anterior
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarI;
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField idBuscar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}