/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzeria.IU;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class VentaRegistradaGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentaRegistradaGUI.class.getName());
    private String nombreUsuario;
    private String rolUsuario;
    private javax.swing.JButton btnActivo = null;

    /**
     * Creates new form MenuGerente
     */
   public VentaRegistradaGUI() {
    initComponents();

    this.rolUsuario = "Cajero";
    this.nombreUsuario = "";

    inicializarVentanaVentaRegistrada();
}

public VentaRegistradaGUI(String rol, String nombre) {
    initComponents();

    this.rolUsuario = rol;
    this.nombreUsuario = nombre;

    inicializarVentanaVentaRegistrada();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rol = new javax.swing.JLabel();
        BarraNav = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        PiePag = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Interfaz = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblNumeroVentaRegistrada = new javax.swing.JLabel();
        lblClienteRegistrado = new javax.swing.JLabel();
        lblMetodoPagoRegistrado = new javax.swing.JLabel();
        lblEstadoRegistrado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lblTotalRegistrado = new javax.swing.JLabel();
        lblCambioRegistrado = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        Encabezado.setBackground(new java.awt.Color(168, 27, 29));
        Encabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LA CASA DEL SABOR");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("LOGO");
        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIZZERIA");

        Rol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rol.setForeground(new java.awt.Color(255, 255, 255));
        Rol.setText("Cajero");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BarraNav.setBackground(new java.awt.Color(28, 28, 28));
        BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        btnInicio.setBackground(new java.awt.Color(168, 27, 29));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ventas");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnUsuarios.setBackground(new java.awt.Color(28, 28, 28));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Reservas");
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnReportes.setBackground(new java.awt.Color(28, 28, 28));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Ver Menu");
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnCerrar.setBackground(new java.awt.Color(28, 28, 28));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout BarraNavLayout = new javax.swing.GroupLayout(BarraNav);
        BarraNav.setLayout(BarraNavLayout);
        BarraNavLayout.setHorizontalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BarraNavLayout.setVerticalGroup(
            BarraNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNavLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
        );

        PiePag.setBackground(new java.awt.Color(28, 28, 28));
        PiePag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Powered by StarTech");

        jLabel5.setText("Logo");

        javax.swing.GroupLayout PiePagLayout = new javax.swing.GroupLayout(PiePag);
        PiePag.setLayout(PiePagLayout);
        PiePagLayout.setHorizontalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PiePagLayout.setVerticalGroup(
            PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiePagLayout.createSequentialGroup()
                .addGroup(PiePagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        Interfaz.setBackground(new java.awt.Color(255, 255, 255));
        Interfaz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(168, 27, 29));
        jLabel19.setText("VENTA REGISTRADA");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        jLabel6.setText("Venta registrada correctamente");

        jButton1.setBackground(new java.awt.Color(168, 27, 29));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NUEVO PEDIDO");
        jButton1.setAlignmentX(82.0F);
        jButton1.setAlignmentY(145.0F);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton2.setText("VER HISTORIAL");
        jButton2.setAlignmentX(345.0F);
        jButton2.setAlignmentY(145.0F);
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));
        jButton2.addActionListener(this::jButton2ActionPerformed);

        lblNumeroVentaRegistrada.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        lblNumeroVentaRegistrada.setText("Venta N.º 001");

        lblClienteRegistrado.setText("Cliente: Juan Pérez");

        lblMetodoPagoRegistrado.setText("Método de pago: Efectivo");

        lblEstadoRegistrado.setText("Estado: Pendiente para cocina");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel7.setText("OK");

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(168, 27, 29));
        jLabel13.setText("TOTAL");

        lblTotalRegistrado.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        lblTotalRegistrado.setForeground(new java.awt.Color(168, 27, 29));
        lblTotalRegistrado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalRegistrado.setText("Bs.  45");

        lblCambioRegistrado.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblCambioRegistrado.setText("Cambio: Bs. 0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMetodoPagoRegistrado)
                            .addComponent(lblClienteRegistrado)
                            .addComponent(lblNumeroVentaRegistrada)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEstadoRegistrado)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(100, 100, 100)
                                .addComponent(lblTotalRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCambioRegistrado)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblNumeroVentaRegistrada)
                .addGap(18, 18, 18)
                .addComponent(lblClienteRegistrado)
                .addGap(18, 18, 18)
                .addComponent(lblMetodoPagoRegistrado)
                .addGap(18, 18, 18)
                .addComponent(lblEstadoRegistrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCambioRegistrado)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblTotalRegistrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout InterfazLayout = new javax.swing.GroupLayout(Interfaz);
        Interfaz.setLayout(InterfazLayout);
        InterfazLayout.setHorizontalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        InterfazLayout.setVerticalGroup(
            InterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(BarraNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PiePag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarraNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Interfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PiePag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        new VentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new ConsultarReservasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FrameVerMenu ventana = new FrameVerMenu(rolUsuario, nombreUsuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this, "¿Desea cerrar sesión?", "Cerrar Sesión",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        new LoginGUI().setVisible(true);
    }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ContextoVentasGUI.getInstancia()
            .getGestorVenta()
            .cancelarArmadoPedido();

    ContextoVentasGUI.getInstancia()
            .getGestorVenta()
            .crearVenta(1);

    new NuevoPedidoGUI(rolUsuario, nombreUsuario).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ConsultarVentasGUI(rolUsuario,nombreUsuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void mostrarUsuario() {
    
        if (rolUsuario == null || rolUsuario.trim().isEmpty()) {
        rolUsuario = "Cajero";
    }

    if (nombreUsuario == null) {
        nombreUsuario = "";
    }

    if (nombreUsuario.trim().isEmpty()) {
        Rol.setText(rolUsuario);
    } else {
        Rol.setText(rolUsuario + ": " + nombreUsuario);
    }
    }
    
    private void cargarPanel(javax.swing.JPanel panel) {
        Interfaz.removeAll();                    // limpia el contenido anterior
        Interfaz.setLayout(new java.awt.BorderLayout());
        Interfaz.add(panel, java.awt.BorderLayout.CENTER);
        Interfaz.revalidate();                   // refresca el layout
        Interfaz.repaint();                      // redibuja
    }
    private void configurarHover() {
        javax.swing.JButton[] botones = {
            btnInicio,
            btnUsuarios,
            btnReportes,
            btnCerrar
        };
    
        for (javax.swing.JButton b : botones) {
            b.setContentAreaFilled(true);
            b.setOpaque(true);
            b.setBorderPainted(false);
            b.setBackground(java.awt.Color.WHITE);
            b.setForeground(new java.awt.Color(60, 60, 60));
        
            b.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(230, 230, 230));
            b.setForeground(new java.awt.Color(168, 27, 29)); // #A81B1D
        }
    }
    @Override
    public void mouseExited(java.awt.event.MouseEvent e) {
        if (b != btnActivo) {
            b.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            b.setForeground(new java.awt.Color(60, 60, 60));
        }
    }
});
        }
    }
    
    private void activarBoton(javax.swing.JButton boton) {
    // Resetea el anterior
        if (btnActivo != null) {
            btnActivo.setBackground(new java.awt.Color(255, 255, 255)); // #FFFFFF
            btnActivo.setForeground(new java.awt.Color(60, 60, 60));
        }
        boton.setBackground(new java.awt.Color(168, 27, 29)); // #A81B1D
        boton.setForeground(new java.awt.Color(255, 255, 255)); // #FFFFFF
        btnActivo = boton;
    }
    
    private void cargarDatosVentaRegistrada() {
                pizzeria.model.Venta venta = ContextoVentasGUI.getInstancia()
            .getUltimaVentaRegistrada();

    ContextoVentasGUI contexto = ContextoVentasGUI.getInstancia();

    String clienteContexto = textoSeguro(contexto.getClienteCobro(), "Sin nombre");
    String metodoContexto = textoSeguro(contexto.getMetodoPagoCobro(), "No especificado");

    if (venta == null) {
        lblNumeroVentaRegistrada.setText("Venta N.º -");
        lblClienteRegistrado.setText("Cliente: " + clienteContexto);
        lblMetodoPagoRegistrado.setText("Método de pago: " + metodoContexto);
        lblEstadoRegistrado.setText("Estado: Registrado");
        lblTotalRegistrado.setText("Bs. 0.00");
        lblCambioRegistrado.setText("Cambio: Bs. "
                + String.format("%.2f", contexto.getCambioCobro()));
        return;
    }

    venta.calcularTotal();

    String cliente = textoSeguro(venta.getNombreCliente(), clienteContexto);

    lblNumeroVentaRegistrada.setText("Venta N.º " + String.format("%03d", venta.getId()));
    lblClienteRegistrado.setText("Cliente: " + cliente);
    lblMetodoPagoRegistrado.setText("Método de pago: " + metodoContexto);
    lblEstadoRegistrado.setText("Estado: " + obtenerEstadoVentaRegistradaVisual(venta));
    lblTotalRegistrado.setText("Bs. " + String.format("%.2f", venta.getTotal()));
    lblCambioRegistrado.setText("Cambio: Bs. "
            + String.format("%.2f", contexto.getCambioCobro()));
    }
    
    private String textoSeguro(String valor, String defecto) {
    if (valor == null || valor.trim().isEmpty()) {
        return defecto;
    }

    return valor.trim();
}
    
    
    private String obtenerEstadoVentaRegistradaVisual(pizzeria.model.Venta venta) {
    if (venta == null || venta.getEstado() == null) {
        return "Registrada";
    }

    switch (venta.getEstado()) {
        case PENDIENTE:
            return "Pendiente para cocina";
        case EN_PREPARACION:
            return "En preparación";
        case LISTO:
            return "Listo para entregar";
        case ENTREGADO:
            return "Entregado";
        case CANCELADO:
            return "Cancelado";
        default:
            return venta.getEstado().name();
    }
}
    private void inicializarVentanaVentaRegistrada() {
    aplicarEstructuraVisualCajero();
    reconstruirInterfazVentaRegistrada();

    mostrarUsuario();
    configurarHover();
    activarBoton(btnInicio);

    cargarImagen(lblLogo, "resources/imagenes/logoCasaDelSabor.jpeg");
    cargarDatosVentaRegistrada();
}
    private void aplicarEstructuraVisualCajero() {
    setSize(1280, 720);
    setMinimumSize(new java.awt.Dimension(1280, 720));
    setMaximumSize(new java.awt.Dimension(1280, 720));
    setPreferredSize(new java.awt.Dimension(1280, 720));
    setResizable(false);
    setLocationRelativeTo(null);

    if (lblLogo != null) {
        lblLogo.setPreferredSize(new java.awt.Dimension(75, 75));
        lblLogo.setMinimumSize(new java.awt.Dimension(75, 75));
        lblLogo.setMaximumSize(new java.awt.Dimension(75, 75));
    }

    Encabezado.setPreferredSize(new java.awt.Dimension(1280, 100));
    Encabezado.setMinimumSize(new java.awt.Dimension(1280, 100));

    PiePag.setPreferredSize(new java.awt.Dimension(1280, 47));
    PiePag.setMinimumSize(new java.awt.Dimension(1280, 47));

    BarraNav.setPreferredSize(new java.awt.Dimension(280, 573));
    BarraNav.setMinimumSize(new java.awt.Dimension(280, 573));
    BarraNav.setMaximumSize(new java.awt.Dimension(280, 573));

    Interfaz.setPreferredSize(new java.awt.Dimension(1000, 573));
    Interfaz.setBackground(java.awt.Color.WHITE);

    reconstruirEstructuraBaseCajero();

    revalidate();
    repaint();
}
   
    
    private void reconstruirEstructuraBaseCajero() {
    getContentPane().removeAll();

    Fondo.removeAll();
    Fondo.setLayout(new java.awt.BorderLayout(0, 0));
    Fondo.setBackground(java.awt.Color.WHITE);

    configurarBarraLateral();

    javax.swing.JPanel cuerpo = new javax.swing.JPanel(new java.awt.BorderLayout(0, 0));
    cuerpo.setBackground(java.awt.Color.WHITE);
    cuerpo.setPreferredSize(new java.awt.Dimension(1280, 573));
    cuerpo.add(BarraNav, java.awt.BorderLayout.WEST);
    cuerpo.add(Interfaz, java.awt.BorderLayout.CENTER);

    Fondo.add(Encabezado, java.awt.BorderLayout.NORTH);
    Fondo.add(cuerpo, java.awt.BorderLayout.CENTER);
    Fondo.add(PiePag, java.awt.BorderLayout.SOUTH);

    setContentPane(Fondo);
}
    
    private void configurarBarraLateral() {
    BarraNav.removeAll();
    BarraNav.setLayout(new javax.swing.BoxLayout(BarraNav, javax.swing.BoxLayout.Y_AXIS));
    BarraNav.setBackground(new java.awt.Color(28, 28, 28));
    BarraNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

    java.awt.Dimension tamBoton = new java.awt.Dimension(250, 60);

    configurarBotonLateral(btnInicio, tamBoton);
    configurarBotonLateral(btnUsuarios, tamBoton);
    configurarBotonLateral(btnReportes, tamBoton);
    configurarBotonLateral(btnCerrar, tamBoton);

    BarraNav.add(javax.swing.Box.createVerticalStrut(58));
    BarraNav.add(btnInicio);
    BarraNav.add(javax.swing.Box.createVerticalStrut(60));
    BarraNav.add(btnUsuarios);
    BarraNav.add(javax.swing.Box.createVerticalStrut(49));
    BarraNav.add(btnReportes);
    BarraNav.add(javax.swing.Box.createVerticalStrut(55));
    BarraNav.add(btnCerrar);
    BarraNav.add(javax.swing.Box.createVerticalGlue());
}
    
    
    private void configurarBotonLateral(javax.swing.JButton boton, java.awt.Dimension tamano) {
    boton.setPreferredSize(tamano);
    boton.setMinimumSize(tamano);
    boton.setMaximumSize(tamano);
    boton.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    boton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    boton.setFocusPainted(false);
}
    
    private void reconstruirInterfazVentaRegistrada() {
    Interfaz.removeAll();
    Interfaz.setLayout(new java.awt.BorderLayout());
    Interfaz.setBackground(java.awt.Color.WHITE);
    Interfaz.setBorder(javax.swing.BorderFactory.createEmptyBorder(45, 70, 45, 70));

    javax.swing.JPanel panelContenido = new javax.swing.JPanel();
    panelContenido.setOpaque(false);
    panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));

    jLabel19.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

    jPanel2.removeAll();
    jPanel2.setBackground(java.awt.Color.WHITE);
    jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)),
            javax.swing.BorderFactory.createEmptyBorder(25, 35, 25, 35)
    ));
    jPanel2.setMaximumSize(new java.awt.Dimension(720, 420));
    jPanel2.setPreferredSize(new java.awt.Dimension(720, 420));
    jPanel2.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    jPanel2.setLayout(new java.awt.BorderLayout());

    javax.swing.JPanel panelSuperior = new javax.swing.JPanel();
    panelSuperior.setOpaque(false);
    panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.Y_AXIS));

    jLabel7.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    jLabel6.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    jSeparator1.setMaximumSize(new java.awt.Dimension(620, 10));

    panelSuperior.add(jLabel7);
    panelSuperior.add(javax.swing.Box.createVerticalStrut(5));
    panelSuperior.add(jLabel6);
    panelSuperior.add(javax.swing.Box.createVerticalStrut(10));
    panelSuperior.add(jSeparator1);

    javax.swing.JPanel panelDatos = new javax.swing.JPanel();
    panelDatos.setOpaque(false);
    panelDatos.setLayout(new javax.swing.BoxLayout(panelDatos, javax.swing.BoxLayout.Y_AXIS));
    panelDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 0, 10, 0));

    panelDatos.add(lblNumeroVentaRegistrada);
    panelDatos.add(javax.swing.Box.createVerticalStrut(16));
    panelDatos.add(lblClienteRegistrado);
    panelDatos.add(javax.swing.Box.createVerticalStrut(16));
    panelDatos.add(lblMetodoPagoRegistrado);
    panelDatos.add(javax.swing.Box.createVerticalStrut(16));
    panelDatos.add(lblEstadoRegistrado);
    panelDatos.add(javax.swing.Box.createVerticalStrut(16));
    panelDatos.add(lblCambioRegistrado);
    panelDatos.add(javax.swing.Box.createVerticalStrut(20));

    javax.swing.JPanel panelTotal = new javax.swing.JPanel(new java.awt.BorderLayout());
    panelTotal.setOpaque(false);
    panelTotal.add(jLabel13, java.awt.BorderLayout.WEST);
    panelTotal.add(lblTotalRegistrado, java.awt.BorderLayout.EAST);
    panelDatos.add(panelTotal);

    javax.swing.JPanel panelBotones = new javax.swing.JPanel();
    panelBotones.setOpaque(false);
    panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 55, 0));
    panelBotones.add(jButton1);
    panelBotones.add(jButton2);

    jButton1.setPreferredSize(new java.awt.Dimension(245, 42));
    jButton2.setPreferredSize(new java.awt.Dimension(210, 42));

    jPanel2.add(panelSuperior, java.awt.BorderLayout.NORTH);
    jPanel2.add(panelDatos, java.awt.BorderLayout.CENTER);
    jPanel2.add(panelBotones, java.awt.BorderLayout.SOUTH);

    panelContenido.add(jLabel19);
    panelContenido.add(javax.swing.Box.createVerticalStrut(12));
    panelContenido.add(jPanel2);

    Interfaz.add(panelContenido, java.awt.BorderLayout.CENTER);

    Interfaz.revalidate();
    Interfaz.repaint();
}
    
    
    private void cargarImagen(JLabel label, String ruta) {
    label.setText("");

    try {
        java.io.File archivo = new java.io.File(ruta);

        if (!archivo.exists()) {
            System.err.println("Imagen no encontrada: " + ruta);
            return;
        }

        ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());

        Image imgEscalada = icono.getImage().getScaledInstance(
                label.getPreferredSize().width,
                label.getPreferredSize().height,
                Image.SCALE_SMOOTH
        );

        label.setIcon(new ImageIcon(imgEscalada));

    } catch (Exception e) {
        System.err.println("Error cargando imagen: " + e.getMessage());
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentaRegistradaGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNav;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Interfaz;
    private javax.swing.JPanel PiePag;
    private javax.swing.JLabel Rol;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCambioRegistrado;
    private javax.swing.JLabel lblClienteRegistrado;
    private javax.swing.JLabel lblEstadoRegistrado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMetodoPagoRegistrado;
    private javax.swing.JLabel lblNumeroVentaRegistrada;
    private javax.swing.JLabel lblTotalRegistrado;
    // End of variables declaration//GEN-END:variables
}
